package alga

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"time"
)

// AlgaAuthError is returned for 401/403 responses. Auth errors are never
// retryable — the token must be valid (not revoked, not expired) before
// retrying.
type AlgaAuthError struct {
	StatusCode int
	Message    string
}

func (e *AlgaAuthError) Error() string {
	return fmt.Sprintf("auth error %d: %s", e.StatusCode, e.Message)
}

// AlgaAPIError is returned for any non-2xx, non-auth response. RetryAfter is
// populated from the `Retry-After` header when present (notably for 429s).
type AlgaAPIError struct {
	StatusCode int
	Message    string
	RetryAfter time.Duration
}

func (e *AlgaAPIError) Error() string {
	if e.RetryAfter > 0 {
		return fmt.Sprintf("api error %d: %s (retry after %s)", e.StatusCode, e.Message, e.RetryAfter)
	}
	return fmt.Sprintf("api error %d: %s", e.StatusCode, e.Message)
}

// IsRetryable reports whether the error is worth retrying per the HTTP
// status code (429, 500, 502, 503, 504). 4xx errors other than 429 are
// considered permanent.
func (e *AlgaAPIError) IsRetryable() bool {
	switch e.StatusCode {
	case http.StatusTooManyRequests,
		http.StatusInternalServerError,
		http.StatusBadGateway,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		return true
	default:
		return false
	}
}

// AlgaConnectionError wraps a transport-level error (DNS, TCP, TLS, timeout).
// The underlying error is retained via Unwrap so callers can use errors.As
// to detect net.Error timeouts, etc.
type AlgaConnectionError struct {
	Err error
}

func (e *AlgaConnectionError) Error() string {
	if e.Err == nil {
		return "connection error"
	}
	return fmt.Sprintf("connection error: %v", e.Err)
}

func (e *AlgaConnectionError) Unwrap() error { return e.Err }

// IsRetryable reports whether a connection error is worth retrying.
// Caller-owned context cancellation and deadline expiry (i.e., the caller's
// own ctx was cancelled or deadline-exceeded) are deliberate caller decisions
// and never retried. Transport-level timeouts (net.Error with Timeout() == true)
// and other transport failures (DNS, TCP reset, TLS) are treated as transient
// and retried.
func (e *AlgaConnectionError) IsRetryable() bool {
	if e.Err == nil {
		return false
	}
	// Caller-owned context cancellation is never retryable.
	if errors.Is(e.Err, context.Canceled) {
		return false
	}
	// Caller-owned context deadline is not retryable.
	if errors.Is(e.Err, context.DeadlineExceeded) {
		return false
	}
	// Transport-level timeouts (net.Error.Timeout) are retryable even if they
	// wrap context.DeadlineExceeded, as those are generated by the HTTP client's
	// own timeout, not the caller's context.
	var netErr net.Error
	if errors.As(e.Err, &netErr) && netErr.Timeout() {
		return true
	}
	return true
}

// IsRetryableError reports whether err is a retryable SDK error (an
// AlgaAPIError or AlgaConnectionError whose IsRetryable method returns true).
// Non-SDK errors are reported as non-retryable so callers don't accidentally
// retry a programming bug.
func IsRetryableError(err error) bool {
	var apiErr *AlgaAPIError
	if errors.As(err, &apiErr) {
		return apiErr.IsRetryable()
	}
	var connErr *AlgaConnectionError
	if errors.As(err, &connErr) {
		return connErr.IsRetryable()
	}
	return false
}
