root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "yaml", "yml", "env"]
exclude_dir = ["tmp", "vendor", ".git"]
delay = 200
send_interrupt = true
kill_delay = 500

[log]
time = true
