package rbac

type Permission string

const (
	AlertsRead              Permission = "alerts:read"
	AlertsWrite             Permission = "alerts:write"
	AlertsDelete            Permission = "alerts:delete"
	KnowledgeRead           Permission = "knowledge:read"
	KnowledgeWrite          Permission = "knowledge:write"
	KnowledgeDelete         Permission = "knowledge:delete"
	RoutesRead              Permission = "routes:read"
	RoutesWrite             Permission = "routes:write"
	IntegrationsRead        Permission = "integrations:read"
	IntegrationsWrite       Permission = "integrations:write"
	IntegrationsTest        Permission = "integrations:test"
	UsersManage             Permission = "users:manage"
	TokensManage            Permission = "tokens:manage"
	DashboardRead           Permission = "dashboard:read"
	ChannelsRead            Permission = "channels:read"
	AuditRead               Permission = "audit:read"
	NotificationsRead       Permission = "notifications:read"
	NotificationsWrite      Permission = "notifications:write"
	MemoriesRead            Permission = "memories:read"
	MemoriesWrite           Permission = "memories:write"
	MemoriesDelete          Permission = "memories:delete"
	SystemConfigRead        Permission = "system:read"
	SystemConfigWrite       Permission = "system:write"
	TriageRead              Permission = "triage:read"
	TriageWrite             Permission = "triage:write"
	TriageOverride          Permission = "triage:override"
	IncidentsRead           Permission = "incidents:read"
	IncidentsWrite          Permission = "incidents:write"
	IncidentsCommand        Permission = "incidents:command"
	IncidentsDelete         Permission = "incidents:delete"
	ServicesRead            Permission = "services:read"
	ServicesWrite           Permission = "services:write"
	OnCallRead              Permission = "oncall:read"
	OnCallWrite             Permission = "oncall:write"
	EscalationRead          Permission = "escalation:read"
	EscalationWrite         Permission = "escalation:write"
	PostMortemsRead         Permission = "postmortems:read"
	PostMortemsWrite        Permission = "postmortems:write"
	PostMortemsDelete       Permission = "postmortems:delete"
	PlaybookRead            Permission = "playbooks:read"
	PlaybookWrite           Permission = "playbooks:write"
	PlaybookDelete          Permission = "playbooks:delete"
	HeartbeatsRead          Permission = "heartbeats:read"
	HeartbeatsWrite         Permission = "heartbeats:write"
	HeartbeatsDelete        Permission = "heartbeats:delete"
	StatusPagesRead         Permission = "statuspages:read"
	StatusPagesWrite        Permission = "statuspages:write"
	StatusPagesDelete       Permission = "statuspages:delete"
	OIDCManage              Permission = "oidc:manage"
	CredentialSecretsManage Permission = "credentials:manage"
	CredentialSecretsRead   Permission = "credentials:read"
	AdminAccess             Permission = "admin:access"
)
