// Code generated by ent, DO NOT EDIT.

package investigationthreadmessage

import (
	"alga/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldID, id))
}

// ThreadUUID applies equality check predicate on the "thread_uuid" field. It's identical to ThreadUUIDEQ.
func ThreadUUID(v uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldThreadUUID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldType, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldSource, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldMessage, v))
}

// Internal applies equality check predicate on the "internal" field. It's identical to InternalEQ.
func Internal(v bool) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldInternal, v))
}

// Edited applies equality check predicate on the "edited" field. It's identical to EditedEQ.
func Edited(v bool) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldEdited, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldUserID, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldUsername, v))
}

// AgentType applies equality check predicate on the "agent_type" field. It's identical to AgentTypeEQ.
func AgentType(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldAgentType, v))
}

// MmPostID applies equality check predicate on the "mm_post_id" field. It's identical to MmPostIDEQ.
func MmPostID(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldMmPostID, v))
}

// SlackMessageTs applies equality check predicate on the "slack_message_ts" field. It's identical to SlackMessageTsEQ.
func SlackMessageTs(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldSlackMessageTs, v))
}

// ReplyToMessageID applies equality check predicate on the "reply_to_message_id" field. It's identical to ReplyToMessageIDEQ.
func ReplyToMessageID(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldReplyToMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// ThreadUUIDEQ applies the EQ predicate on the "thread_uuid" field.
func ThreadUUIDEQ(v uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldThreadUUID, v))
}

// ThreadUUIDNEQ applies the NEQ predicate on the "thread_uuid" field.
func ThreadUUIDNEQ(v uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldThreadUUID, v))
}

// ThreadUUIDIn applies the In predicate on the "thread_uuid" field.
func ThreadUUIDIn(vs ...uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldThreadUUID, vs...))
}

// ThreadUUIDNotIn applies the NotIn predicate on the "thread_uuid" field.
func ThreadUUIDNotIn(vs ...uuid.UUID) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldThreadUUID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldType, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldSource, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldMessage, v))
}

// InternalEQ applies the EQ predicate on the "internal" field.
func InternalEQ(v bool) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldInternal, v))
}

// InternalNEQ applies the NEQ predicate on the "internal" field.
func InternalNEQ(v bool) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldInternal, v))
}

// EditedEQ applies the EQ predicate on the "edited" field.
func EditedEQ(v bool) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldEdited, v))
}

// EditedNEQ applies the NEQ predicate on the "edited" field.
func EditedNEQ(v bool) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldEdited, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldUserID))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldUserID, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldUsername, v))
}

// AgentTypeEQ applies the EQ predicate on the "agent_type" field.
func AgentTypeEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldAgentType, v))
}

// AgentTypeNEQ applies the NEQ predicate on the "agent_type" field.
func AgentTypeNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldAgentType, v))
}

// AgentTypeIn applies the In predicate on the "agent_type" field.
func AgentTypeIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldAgentType, vs...))
}

// AgentTypeNotIn applies the NotIn predicate on the "agent_type" field.
func AgentTypeNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldAgentType, vs...))
}

// AgentTypeGT applies the GT predicate on the "agent_type" field.
func AgentTypeGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldAgentType, v))
}

// AgentTypeGTE applies the GTE predicate on the "agent_type" field.
func AgentTypeGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldAgentType, v))
}

// AgentTypeLT applies the LT predicate on the "agent_type" field.
func AgentTypeLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldAgentType, v))
}

// AgentTypeLTE applies the LTE predicate on the "agent_type" field.
func AgentTypeLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldAgentType, v))
}

// AgentTypeContains applies the Contains predicate on the "agent_type" field.
func AgentTypeContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldAgentType, v))
}

// AgentTypeHasPrefix applies the HasPrefix predicate on the "agent_type" field.
func AgentTypeHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldAgentType, v))
}

// AgentTypeHasSuffix applies the HasSuffix predicate on the "agent_type" field.
func AgentTypeHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldAgentType, v))
}

// AgentTypeIsNil applies the IsNil predicate on the "agent_type" field.
func AgentTypeIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldAgentType))
}

// AgentTypeNotNil applies the NotNil predicate on the "agent_type" field.
func AgentTypeNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldAgentType))
}

// AgentTypeEqualFold applies the EqualFold predicate on the "agent_type" field.
func AgentTypeEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldAgentType, v))
}

// AgentTypeContainsFold applies the ContainsFold predicate on the "agent_type" field.
func AgentTypeContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldAgentType, v))
}

// MmPostIDEQ applies the EQ predicate on the "mm_post_id" field.
func MmPostIDEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldMmPostID, v))
}

// MmPostIDNEQ applies the NEQ predicate on the "mm_post_id" field.
func MmPostIDNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldMmPostID, v))
}

// MmPostIDIn applies the In predicate on the "mm_post_id" field.
func MmPostIDIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldMmPostID, vs...))
}

// MmPostIDNotIn applies the NotIn predicate on the "mm_post_id" field.
func MmPostIDNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldMmPostID, vs...))
}

// MmPostIDGT applies the GT predicate on the "mm_post_id" field.
func MmPostIDGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldMmPostID, v))
}

// MmPostIDGTE applies the GTE predicate on the "mm_post_id" field.
func MmPostIDGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldMmPostID, v))
}

// MmPostIDLT applies the LT predicate on the "mm_post_id" field.
func MmPostIDLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldMmPostID, v))
}

// MmPostIDLTE applies the LTE predicate on the "mm_post_id" field.
func MmPostIDLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldMmPostID, v))
}

// MmPostIDContains applies the Contains predicate on the "mm_post_id" field.
func MmPostIDContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldMmPostID, v))
}

// MmPostIDHasPrefix applies the HasPrefix predicate on the "mm_post_id" field.
func MmPostIDHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldMmPostID, v))
}

// MmPostIDHasSuffix applies the HasSuffix predicate on the "mm_post_id" field.
func MmPostIDHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldMmPostID, v))
}

// MmPostIDIsNil applies the IsNil predicate on the "mm_post_id" field.
func MmPostIDIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldMmPostID))
}

// MmPostIDNotNil applies the NotNil predicate on the "mm_post_id" field.
func MmPostIDNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldMmPostID))
}

// MmPostIDEqualFold applies the EqualFold predicate on the "mm_post_id" field.
func MmPostIDEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldMmPostID, v))
}

// MmPostIDContainsFold applies the ContainsFold predicate on the "mm_post_id" field.
func MmPostIDContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldMmPostID, v))
}

// SlackMessageTsEQ applies the EQ predicate on the "slack_message_ts" field.
func SlackMessageTsEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldSlackMessageTs, v))
}

// SlackMessageTsNEQ applies the NEQ predicate on the "slack_message_ts" field.
func SlackMessageTsNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldSlackMessageTs, v))
}

// SlackMessageTsIn applies the In predicate on the "slack_message_ts" field.
func SlackMessageTsIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldSlackMessageTs, vs...))
}

// SlackMessageTsNotIn applies the NotIn predicate on the "slack_message_ts" field.
func SlackMessageTsNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldSlackMessageTs, vs...))
}

// SlackMessageTsGT applies the GT predicate on the "slack_message_ts" field.
func SlackMessageTsGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldSlackMessageTs, v))
}

// SlackMessageTsGTE applies the GTE predicate on the "slack_message_ts" field.
func SlackMessageTsGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldSlackMessageTs, v))
}

// SlackMessageTsLT applies the LT predicate on the "slack_message_ts" field.
func SlackMessageTsLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldSlackMessageTs, v))
}

// SlackMessageTsLTE applies the LTE predicate on the "slack_message_ts" field.
func SlackMessageTsLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldSlackMessageTs, v))
}

// SlackMessageTsContains applies the Contains predicate on the "slack_message_ts" field.
func SlackMessageTsContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldSlackMessageTs, v))
}

// SlackMessageTsHasPrefix applies the HasPrefix predicate on the "slack_message_ts" field.
func SlackMessageTsHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldSlackMessageTs, v))
}

// SlackMessageTsHasSuffix applies the HasSuffix predicate on the "slack_message_ts" field.
func SlackMessageTsHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldSlackMessageTs, v))
}

// SlackMessageTsIsNil applies the IsNil predicate on the "slack_message_ts" field.
func SlackMessageTsIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldSlackMessageTs))
}

// SlackMessageTsNotNil applies the NotNil predicate on the "slack_message_ts" field.
func SlackMessageTsNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldSlackMessageTs))
}

// SlackMessageTsEqualFold applies the EqualFold predicate on the "slack_message_ts" field.
func SlackMessageTsEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldSlackMessageTs, v))
}

// SlackMessageTsContainsFold applies the ContainsFold predicate on the "slack_message_ts" field.
func SlackMessageTsContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldSlackMessageTs, v))
}

// ReplyToMessageIDEQ applies the EQ predicate on the "reply_to_message_id" field.
func ReplyToMessageIDEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldReplyToMessageID, v))
}

// ReplyToMessageIDNEQ applies the NEQ predicate on the "reply_to_message_id" field.
func ReplyToMessageIDNEQ(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldReplyToMessageID, v))
}

// ReplyToMessageIDIn applies the In predicate on the "reply_to_message_id" field.
func ReplyToMessageIDIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldReplyToMessageID, vs...))
}

// ReplyToMessageIDNotIn applies the NotIn predicate on the "reply_to_message_id" field.
func ReplyToMessageIDNotIn(vs ...string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldReplyToMessageID, vs...))
}

// ReplyToMessageIDGT applies the GT predicate on the "reply_to_message_id" field.
func ReplyToMessageIDGT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldReplyToMessageID, v))
}

// ReplyToMessageIDGTE applies the GTE predicate on the "reply_to_message_id" field.
func ReplyToMessageIDGTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldReplyToMessageID, v))
}

// ReplyToMessageIDLT applies the LT predicate on the "reply_to_message_id" field.
func ReplyToMessageIDLT(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldReplyToMessageID, v))
}

// ReplyToMessageIDLTE applies the LTE predicate on the "reply_to_message_id" field.
func ReplyToMessageIDLTE(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldReplyToMessageID, v))
}

// ReplyToMessageIDContains applies the Contains predicate on the "reply_to_message_id" field.
func ReplyToMessageIDContains(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContains(FieldReplyToMessageID, v))
}

// ReplyToMessageIDHasPrefix applies the HasPrefix predicate on the "reply_to_message_id" field.
func ReplyToMessageIDHasPrefix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasPrefix(FieldReplyToMessageID, v))
}

// ReplyToMessageIDHasSuffix applies the HasSuffix predicate on the "reply_to_message_id" field.
func ReplyToMessageIDHasSuffix(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldHasSuffix(FieldReplyToMessageID, v))
}

// ReplyToMessageIDIsNil applies the IsNil predicate on the "reply_to_message_id" field.
func ReplyToMessageIDIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldReplyToMessageID))
}

// ReplyToMessageIDNotNil applies the NotNil predicate on the "reply_to_message_id" field.
func ReplyToMessageIDNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldReplyToMessageID))
}

// ReplyToMessageIDEqualFold applies the EqualFold predicate on the "reply_to_message_id" field.
func ReplyToMessageIDEqualFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEqualFold(FieldReplyToMessageID, v))
}

// ReplyToMessageIDContainsFold applies the ContainsFold predicate on the "reply_to_message_id" field.
func ReplyToMessageIDContainsFold(v string) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldContainsFold(FieldReplyToMessageID, v))
}

// MentionsIsNil applies the IsNil predicate on the "mentions" field.
func MentionsIsNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIsNull(FieldMentions))
}

// MentionsNotNil applies the NotNil predicate on the "mentions" field.
func MentionsNotNil() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotNull(FieldMentions))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasThread applies the HasEdge predicate on the "thread" edge.
func HasThread() predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ThreadTable, ThreadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThreadWith applies the HasEdge predicate on the "thread" edge with a given conditions (other predicates).
func HasThreadWith(preds ...predicate.InvestigationThread) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(func(s *sql.Selector) {
		step := newThreadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvestigationThreadMessage) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvestigationThreadMessage) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvestigationThreadMessage) predicate.InvestigationThreadMessage {
	return predicate.InvestigationThreadMessage(sql.NotPredicates(p))
}
