// Code generated by ent, DO NOT EDIT.

package playbookstep

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the playbookstep type in the database.
	Label = "playbook_step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaybookID holds the string denoting the playbook_id field in the database.
	FieldPlaybookID = "playbook_id"
	// FieldStepNumber holds the string denoting the step_number field in the database.
	FieldStepNumber = "step_number"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldExpectedDuration holds the string denoting the expected_duration field in the database.
	FieldExpectedDuration = "expected_duration"
	// FieldCommand holds the string denoting the command field in the database.
	FieldCommand = "command"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlaybook holds the string denoting the playbook edge name in mutations.
	EdgePlaybook = "playbook"
	// Table holds the table name of the playbookstep in the database.
	Table = "playbook_steps"
	// PlaybookTable is the table that holds the playbook relation/edge.
	PlaybookTable = "playbook_steps"
	// PlaybookInverseTable is the table name for the Playbook entity.
	// It exists in this package in order to avoid circular dependency with the "playbook" package.
	PlaybookInverseTable = "playbooks"
	// PlaybookColumn is the table column denoting the playbook relation/edge.
	PlaybookColumn = "playbook_id"
)

// Columns holds all SQL columns for playbookstep fields.
var Columns = []string{
	FieldID,
	FieldPlaybookID,
	FieldStepNumber,
	FieldTitle,
	FieldDescription,
	FieldExpectedDuration,
	FieldCommand,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StepNumberValidator is a validator for the "step_number" field. It is called by the builders before save.
	StepNumberValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PlaybookStep queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlaybookID orders the results by the playbook_id field.
func ByPlaybookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaybookID, opts...).ToFunc()
}

// ByStepNumber orders the results by the step_number field.
func ByStepNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepNumber, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByExpectedDuration orders the results by the expected_duration field.
func ByExpectedDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedDuration, opts...).ToFunc()
}

// ByCommand orders the results by the command field.
func ByCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommand, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlaybookField orders the results by playbook field.
func ByPlaybookField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlaybookStep(), sql.OrderByField(field, opts...))
	}
}
func newPlaybookStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlaybookInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlaybookTable, PlaybookColumn),
	)
}
