// Code generated by ent, DO NOT EDIT.

package agentdmmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agentdmmessage type in the database.
	Label = "agent_dm_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEdited holds the string denoting the edited field in the database.
	FieldEdited = "edited"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAgentTokenID holds the string denoting the agent_token_id field in the database.
	FieldAgentTokenID = "agent_token_id"
	// EdgeAgentToken holds the string denoting the agent_token edge name in mutations.
	EdgeAgentToken = "agent_token"
	// Table holds the table name of the agentdmmessage in the database.
	Table = "agent_dm_messages"
	// AgentTokenTable is the table that holds the agent_token relation/edge.
	AgentTokenTable = "agent_dm_messages"
	// AgentTokenInverseTable is the table name for the AgentToken entity.
	// It exists in this package in order to avoid circular dependency with the "agenttoken" package.
	AgentTokenInverseTable = "agent_tokens"
	// AgentTokenColumn is the table column denoting the agent_token relation/edge.
	AgentTokenColumn = "agent_token_id"
)

// Columns holds all SQL columns for agentdmmessage fields.
var Columns = []string{
	FieldID,
	FieldChatID,
	FieldRole,
	FieldBody,
	FieldUserID,
	FieldUsername,
	FieldEdited,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAgentTokenID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultChatID holds the default value on creation for the "chat_id" field.
	DefaultChatID string
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
	// DefaultEdited holds the default value on creation for the "edited" field.
	DefaultEdited bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AgentDMMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEdited orders the results by the edited field.
func ByEdited(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEdited, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAgentTokenID orders the results by the agent_token_id field.
func ByAgentTokenID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentTokenID, opts...).ToFunc()
}

// ByAgentTokenField orders the results by agent_token field.
func ByAgentTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentTokenStep(), sql.OrderByField(field, opts...))
	}
}
func newAgentTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentTokenInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AgentTokenTable, AgentTokenColumn),
	)
}
