// Code generated by ent, DO NOT EDIT.

package schedulelayer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the schedulelayer type in the database.
	Label = "schedule_layer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScheduleID holds the string denoting the schedule_id field in the database.
	FieldScheduleID = "schedule_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRotationType holds the string denoting the rotation_type field in the database.
	FieldRotationType = "rotation_type"
	// FieldRotationInterval holds the string denoting the rotation_interval field in the database.
	FieldRotationInterval = "rotation_interval"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldDaysOfWeek holds the string denoting the days_of_week field in the database.
	FieldDaysOfWeek = "days_of_week"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldUserIds holds the string denoting the user_ids field in the database.
	FieldUserIds = "user_ids"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSchedule holds the string denoting the schedule edge name in mutations.
	EdgeSchedule = "schedule"
	// Table holds the table name of the schedulelayer in the database.
	Table = "schedule_layers"
	// ScheduleTable is the table that holds the schedule relation/edge.
	ScheduleTable = "schedule_layers"
	// ScheduleInverseTable is the table name for the OnCallSchedule entity.
	// It exists in this package in order to avoid circular dependency with the "oncallschedule" package.
	ScheduleInverseTable = "on_call_schedules"
	// ScheduleColumn is the table column denoting the schedule relation/edge.
	ScheduleColumn = "schedule_id"
)

// Columns holds all SQL columns for schedulelayer fields.
var Columns = []string{
	FieldID,
	FieldScheduleID,
	FieldName,
	FieldRotationType,
	FieldRotationInterval,
	FieldStartDate,
	FieldEndDate,
	FieldTimezone,
	FieldStartTime,
	FieldEndTime,
	FieldDaysOfWeek,
	FieldPriority,
	FieldUserIds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultRotationType holds the default value on creation for the "rotation_type" field.
	DefaultRotationType string
	// DefaultRotationInterval holds the default value on creation for the "rotation_interval" field.
	DefaultRotationInterval int
	// RotationIntervalValidator is a validator for the "rotation_interval" field. It is called by the builders before save.
	RotationIntervalValidator func(int) error
	// DefaultStartDate holds the default value on creation for the "start_date" field.
	DefaultStartDate func() time.Time
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// DefaultStartTime holds the default value on creation for the "start_time" field.
	DefaultStartTime string
	// DefaultEndTime holds the default value on creation for the "end_time" field.
	DefaultEndTime string
	// DefaultDaysOfWeek holds the default value on creation for the "days_of_week" field.
	DefaultDaysOfWeek []string
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	PriorityValidator func(int) error
	// DefaultUserIds holds the default value on creation for the "user_ids" field.
	DefaultUserIds []string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ScheduleLayer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScheduleID orders the results by the schedule_id field.
func ByScheduleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRotationType orders the results by the rotation_type field.
func ByRotationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotationType, opts...).ToFunc()
}

// ByRotationInterval orders the results by the rotation_interval field.
func ByRotationInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotationInterval, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScheduleField orders the results by schedule field.
func ByScheduleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScheduleStep(), sql.OrderByField(field, opts...))
	}
}
func newScheduleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScheduleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ScheduleTable, ScheduleColumn),
	)
}
