// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/actionitem"
	"alga/ent/postmortem"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ActionItemCreate is the builder for creating a ActionItem entity.
type ActionItemCreate struct {
	config
	mutation *ActionItemMutation
	hooks    []Hook
}

// SetPostMortemID sets the "post_mortem_id" field.
func (_c *ActionItemCreate) SetPostMortemID(v uuid.UUID) *ActionItemCreate {
	_c.mutation.SetPostMortemID(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ActionItemCreate) SetDescription(v string) *ActionItemCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ActionItemCreate) SetType(v string) *ActionItemCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableType(v *string) *ActionItemCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetAssigneeName sets the "assignee_name" field.
func (_c *ActionItemCreate) SetAssigneeName(v string) *ActionItemCreate {
	_c.mutation.SetAssigneeName(v)
	return _c
}

// SetNillableAssigneeName sets the "assignee_name" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableAssigneeName(v *string) *ActionItemCreate {
	if v != nil {
		_c.SetAssigneeName(*v)
	}
	return _c
}

// SetAssigneeID sets the "assignee_id" field.
func (_c *ActionItemCreate) SetAssigneeID(v uuid.UUID) *ActionItemCreate {
	_c.mutation.SetAssigneeID(v)
	return _c
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableAssigneeID(v *uuid.UUID) *ActionItemCreate {
	if v != nil {
		_c.SetAssigneeID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ActionItemCreate) SetStatus(v string) *ActionItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableStatus(v *string) *ActionItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ActionItemCreate) SetPriority(v string) *ActionItemCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillablePriority(v *string) *ActionItemCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *ActionItemCreate) SetDueDate(v time.Time) *ActionItemCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableDueDate(v *time.Time) *ActionItemCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActionItemCreate) SetCreatedAt(v time.Time) *ActionItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableCreatedAt(v *time.Time) *ActionItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ActionItemCreate) SetUpdatedAt(v time.Time) *ActionItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableUpdatedAt(v *time.Time) *ActionItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ActionItemCreate) SetID(v uuid.UUID) *ActionItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ActionItemCreate) SetNillableID(v *uuid.UUID) *ActionItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPostMortem sets the "post_mortem" edge to the PostMortem entity.
func (_c *ActionItemCreate) SetPostMortem(v *PostMortem) *ActionItemCreate {
	return _c.SetPostMortemID(v.ID)
}

// Mutation returns the ActionItemMutation object of the builder.
func (_c *ActionItemCreate) Mutation() *ActionItemMutation {
	return _c.mutation
}

// Save creates the ActionItem in the database.
func (_c *ActionItemCreate) Save(ctx context.Context) (*ActionItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActionItemCreate) SaveX(ctx context.Context) *ActionItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActionItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActionItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActionItemCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := actionitem.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.AssigneeName(); !ok {
		v := actionitem.DefaultAssigneeName
		_c.mutation.SetAssigneeName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := actionitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := actionitem.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := actionitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := actionitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := actionitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActionItemCreate) check() error {
	if _, ok := _c.mutation.PostMortemID(); !ok {
		return &ValidationError{Name: "post_mortem_id", err: errors.New(`ent: missing required field "ActionItem.post_mortem_id"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ActionItem.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := actionitem.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ActionItem.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ActionItem.type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ActionItem.status"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "ActionItem.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActionItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ActionItem.updated_at"`)}
	}
	if len(_c.mutation.PostMortemIDs()) == 0 {
		return &ValidationError{Name: "post_mortem", err: errors.New(`ent: missing required edge "ActionItem.post_mortem"`)}
	}
	return nil
}

func (_c *ActionItemCreate) sqlSave(ctx context.Context) (*ActionItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActionItemCreate) createSpec() (*ActionItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ActionItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(actionitem.Table, sqlgraph.NewFieldSpec(actionitem.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(actionitem.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(actionitem.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.AssigneeName(); ok {
		_spec.SetField(actionitem.FieldAssigneeName, field.TypeString, value)
		_node.AssigneeName = value
	}
	if value, ok := _c.mutation.AssigneeID(); ok {
		_spec.SetField(actionitem.FieldAssigneeID, field.TypeUUID, value)
		_node.AssigneeID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(actionitem.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(actionitem.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(actionitem.FieldDueDate, field.TypeTime, value)
		_node.DueDate = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(actionitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(actionitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PostMortemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionitem.PostMortemTable,
			Columns: []string{actionitem.PostMortemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postmortem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostMortemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActionItemCreateBulk is the builder for creating many ActionItem entities in bulk.
type ActionItemCreateBulk struct {
	config
	err      error
	builders []*ActionItemCreate
}

// Save creates the ActionItem entities in the database.
func (_c *ActionItemCreateBulk) Save(ctx context.Context) ([]*ActionItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActionItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActionItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActionItemCreateBulk) SaveX(ctx context.Context) []*ActionItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActionItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActionItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
