// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/agenttoken"
	"alga/ent/schema"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AgentToken is the model entity for the AgentToken schema.
type AgentToken struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AgentType holds the value of the "agent_type" field.
	AgentType agenttoken.AgentType `json:"agent_type,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"-"`
	// LookupPrefix holds the value of the "lookup_prefix" field.
	LookupPrefix string `json:"lookup_prefix,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Revoked holds the value of the "revoked" field.
	Revoked bool `json:"revoked,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// LabelSelectors holds the value of the "label_selectors" field.
	LabelSelectors []schema.RouteCondition `json:"label_selectors,omitempty"`
	// DefaultForInvestigation holds the value of the "default_for_investigation" field.
	DefaultForInvestigation bool `json:"default_for_investigation,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities []string `json:"capabilities,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentTokenQuery when eager-loading is set.
	Edges        AgentTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentTokenEdges holds the relations/edges for other nodes in the graph.
type AgentTokenEdges struct {
	// DmMessages holds the value of the dm_messages edge.
	DmMessages []*AgentDMMessage `json:"dm_messages,omitempty"`
	// IcsRoles holds the value of the ics_roles edge.
	IcsRoles []*ICSRoleAssignment `json:"ics_roles,omitempty"`
	// Memories holds the value of the memories edge.
	Memories []*AgentMemory `json:"memories,omitempty"`
	// SentAsks holds the value of the sent_asks edge.
	SentAsks []*AgentAsk `json:"sent_asks,omitempty"`
	// ReceivedAsks holds the value of the received_asks edge.
	ReceivedAsks []*AgentAsk `json:"received_asks,omitempty"`
	// RepliedAsks holds the value of the replied_asks edge.
	RepliedAsks []*AgentAsk `json:"replied_asks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// DmMessagesOrErr returns the DmMessages value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTokenEdges) DmMessagesOrErr() ([]*AgentDMMessage, error) {
	if e.loadedTypes[0] {
		return e.DmMessages, nil
	}
	return nil, &NotLoadedError{edge: "dm_messages"}
}

// IcsRolesOrErr returns the IcsRoles value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTokenEdges) IcsRolesOrErr() ([]*ICSRoleAssignment, error) {
	if e.loadedTypes[1] {
		return e.IcsRoles, nil
	}
	return nil, &NotLoadedError{edge: "ics_roles"}
}

// MemoriesOrErr returns the Memories value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTokenEdges) MemoriesOrErr() ([]*AgentMemory, error) {
	if e.loadedTypes[2] {
		return e.Memories, nil
	}
	return nil, &NotLoadedError{edge: "memories"}
}

// SentAsksOrErr returns the SentAsks value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTokenEdges) SentAsksOrErr() ([]*AgentAsk, error) {
	if e.loadedTypes[3] {
		return e.SentAsks, nil
	}
	return nil, &NotLoadedError{edge: "sent_asks"}
}

// ReceivedAsksOrErr returns the ReceivedAsks value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTokenEdges) ReceivedAsksOrErr() ([]*AgentAsk, error) {
	if e.loadedTypes[4] {
		return e.ReceivedAsks, nil
	}
	return nil, &NotLoadedError{edge: "received_asks"}
}

// RepliedAsksOrErr returns the RepliedAsks value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTokenEdges) RepliedAsksOrErr() ([]*AgentAsk, error) {
	if e.loadedTypes[5] {
		return e.RepliedAsks, nil
	}
	return nil, &NotLoadedError{edge: "replied_asks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agenttoken.FieldLabelSelectors, agenttoken.FieldCapabilities:
			values[i] = new([]byte)
		case agenttoken.FieldRevoked, agenttoken.FieldEnabled, agenttoken.FieldDefaultForInvestigation:
			values[i] = new(sql.NullBool)
		case agenttoken.FieldName, agenttoken.FieldAgentType, agenttoken.FieldTokenHash, agenttoken.FieldLookupPrefix, agenttoken.FieldScope:
			values[i] = new(sql.NullString)
		case agenttoken.FieldCreatedAt, agenttoken.FieldLastUsedAt, agenttoken.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case agenttoken.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentToken fields.
func (_m *AgentToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agenttoken.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agenttoken.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agenttoken.FieldAgentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_type", values[i])
			} else if value.Valid {
				_m.AgentType = agenttoken.AgentType(value.String)
			}
		case agenttoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case agenttoken.FieldLookupPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lookup_prefix", values[i])
			} else if value.Valid {
				_m.LookupPrefix = value.String
			}
		case agenttoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agenttoken.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case agenttoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case agenttoken.FieldRevoked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revoked", values[i])
			} else if value.Valid {
				_m.Revoked = value.Bool
			}
		case agenttoken.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case agenttoken.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case agenttoken.FieldLabelSelectors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field label_selectors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LabelSelectors); err != nil {
					return fmt.Errorf("unmarshal field label_selectors: %w", err)
				}
			}
		case agenttoken.FieldDefaultForInvestigation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field default_for_investigation", values[i])
			} else if value.Valid {
				_m.DefaultForInvestigation = value.Bool
			}
		case agenttoken.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentToken.
// This includes values selected through modifiers, order, etc.
func (_m *AgentToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDmMessages queries the "dm_messages" edge of the AgentToken entity.
func (_m *AgentToken) QueryDmMessages() *AgentDMMessageQuery {
	return NewAgentTokenClient(_m.config).QueryDmMessages(_m)
}

// QueryIcsRoles queries the "ics_roles" edge of the AgentToken entity.
func (_m *AgentToken) QueryIcsRoles() *ICSRoleAssignmentQuery {
	return NewAgentTokenClient(_m.config).QueryIcsRoles(_m)
}

// QueryMemories queries the "memories" edge of the AgentToken entity.
func (_m *AgentToken) QueryMemories() *AgentMemoryQuery {
	return NewAgentTokenClient(_m.config).QueryMemories(_m)
}

// QuerySentAsks queries the "sent_asks" edge of the AgentToken entity.
func (_m *AgentToken) QuerySentAsks() *AgentAskQuery {
	return NewAgentTokenClient(_m.config).QuerySentAsks(_m)
}

// QueryReceivedAsks queries the "received_asks" edge of the AgentToken entity.
func (_m *AgentToken) QueryReceivedAsks() *AgentAskQuery {
	return NewAgentTokenClient(_m.config).QueryReceivedAsks(_m)
}

// QueryRepliedAsks queries the "replied_asks" edge of the AgentToken entity.
func (_m *AgentToken) QueryRepliedAsks() *AgentAskQuery {
	return NewAgentTokenClient(_m.config).QueryRepliedAsks(_m)
}

// Update returns a builder for updating this AgentToken.
// Note that you need to call AgentToken.Unwrap() before calling this method if this AgentToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentToken) Update() *AgentTokenUpdateOne {
	return NewAgentTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentToken) Unwrap() *AgentToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentToken) String() string {
	var builder strings.Builder
	builder.WriteString("AgentToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("agent_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentType))
	builder.WriteString(", ")
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("lookup_prefix=")
	builder.WriteString(_m.LookupPrefix)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revoked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revoked))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("label_selectors=")
	builder.WriteString(fmt.Sprintf("%v", _m.LabelSelectors))
	builder.WriteString(", ")
	builder.WriteString("default_for_investigation=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultForInvestigation))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteByte(')')
	return builder.String()
}

// AgentTokens is a parsable slice of AgentToken.
type AgentTokens []*AgentToken
