// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/agentdmmessage"
	"alga/ent/agenttoken"
	"alga/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentDMMessageUpdate is the builder for updating AgentDMMessage entities.
type AgentDMMessageUpdate struct {
	config
	hooks    []Hook
	mutation *AgentDMMessageMutation
}

// Where appends a list predicates to the AgentDMMessageUpdate builder.
func (_u *AgentDMMessageUpdate) Where(ps ...predicate.AgentDMMessage) *AgentDMMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *AgentDMMessageUpdate) SetChatID(v string) *AgentDMMessageUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableChatID(v *string) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AgentDMMessageUpdate) SetRole(v agentdmmessage.Role) *AgentDMMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableRole(v *agentdmmessage.Role) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *AgentDMMessageUpdate) SetBody(v string) *AgentDMMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableBody(v *string) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentDMMessageUpdate) SetUserID(v string) *AgentDMMessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableUserID(v *string) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AgentDMMessageUpdate) ClearUserID() *AgentDMMessageUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *AgentDMMessageUpdate) SetUsername(v string) *AgentDMMessageUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableUsername(v *string) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *AgentDMMessageUpdate) ClearUsername() *AgentDMMessageUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetEdited sets the "edited" field.
func (_u *AgentDMMessageUpdate) SetEdited(v bool) *AgentDMMessageUpdate {
	_u.mutation.SetEdited(v)
	return _u
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableEdited(v *bool) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetEdited(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AgentDMMessageUpdate) SetCreatedAt(v time.Time) *AgentDMMessageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableCreatedAt(v *time.Time) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentDMMessageUpdate) SetUpdatedAt(v time.Time) *AgentDMMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAgentTokenID sets the "agent_token_id" field.
func (_u *AgentDMMessageUpdate) SetAgentTokenID(v uuid.UUID) *AgentDMMessageUpdate {
	_u.mutation.SetAgentTokenID(v)
	return _u
}

// SetNillableAgentTokenID sets the "agent_token_id" field if the given value is not nil.
func (_u *AgentDMMessageUpdate) SetNillableAgentTokenID(v *uuid.UUID) *AgentDMMessageUpdate {
	if v != nil {
		_u.SetAgentTokenID(*v)
	}
	return _u
}

// SetAgentToken sets the "agent_token" edge to the AgentToken entity.
func (_u *AgentDMMessageUpdate) SetAgentToken(v *AgentToken) *AgentDMMessageUpdate {
	return _u.SetAgentTokenID(v.ID)
}

// Mutation returns the AgentDMMessageMutation object of the builder.
func (_u *AgentDMMessageUpdate) Mutation() *AgentDMMessageMutation {
	return _u.mutation
}

// ClearAgentToken clears the "agent_token" edge to the AgentToken entity.
func (_u *AgentDMMessageUpdate) ClearAgentToken() *AgentDMMessageUpdate {
	_u.mutation.ClearAgentToken()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentDMMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentDMMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentDMMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentDMMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentDMMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentdmmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentDMMessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := agentdmmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AgentDMMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := agentdmmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "AgentDMMessage.body": %w`, err)}
		}
	}
	if _u.mutation.AgentTokenCleared() && len(_u.mutation.AgentTokenIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentDMMessage.agent_token"`)
	}
	return nil
}

func (_u *AgentDMMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentdmmessage.Table, agentdmmessage.Columns, sqlgraph.NewFieldSpec(agentdmmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(agentdmmessage.FieldChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(agentdmmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(agentdmmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(agentdmmessage.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(agentdmmessage.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(agentdmmessage.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(agentdmmessage.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Edited(); ok {
		_spec.SetField(agentdmmessage.FieldEdited, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(agentdmmessage.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentdmmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AgentTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdmmessage.AgentTokenTable,
			Columns: []string{agentdmmessage.AgentTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdmmessage.AgentTokenTable,
			Columns: []string{agentdmmessage.AgentTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentdmmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentDMMessageUpdateOne is the builder for updating a single AgentDMMessage entity.
type AgentDMMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentDMMessageMutation
}

// SetChatID sets the "chat_id" field.
func (_u *AgentDMMessageUpdateOne) SetChatID(v string) *AgentDMMessageUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableChatID(v *string) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *AgentDMMessageUpdateOne) SetRole(v agentdmmessage.Role) *AgentDMMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableRole(v *agentdmmessage.Role) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *AgentDMMessageUpdateOne) SetBody(v string) *AgentDMMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableBody(v *string) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentDMMessageUpdateOne) SetUserID(v string) *AgentDMMessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableUserID(v *string) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AgentDMMessageUpdateOne) ClearUserID() *AgentDMMessageUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *AgentDMMessageUpdateOne) SetUsername(v string) *AgentDMMessageUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableUsername(v *string) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *AgentDMMessageUpdateOne) ClearUsername() *AgentDMMessageUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetEdited sets the "edited" field.
func (_u *AgentDMMessageUpdateOne) SetEdited(v bool) *AgentDMMessageUpdateOne {
	_u.mutation.SetEdited(v)
	return _u
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableEdited(v *bool) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetEdited(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AgentDMMessageUpdateOne) SetCreatedAt(v time.Time) *AgentDMMessageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableCreatedAt(v *time.Time) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentDMMessageUpdateOne) SetUpdatedAt(v time.Time) *AgentDMMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAgentTokenID sets the "agent_token_id" field.
func (_u *AgentDMMessageUpdateOne) SetAgentTokenID(v uuid.UUID) *AgentDMMessageUpdateOne {
	_u.mutation.SetAgentTokenID(v)
	return _u
}

// SetNillableAgentTokenID sets the "agent_token_id" field if the given value is not nil.
func (_u *AgentDMMessageUpdateOne) SetNillableAgentTokenID(v *uuid.UUID) *AgentDMMessageUpdateOne {
	if v != nil {
		_u.SetAgentTokenID(*v)
	}
	return _u
}

// SetAgentToken sets the "agent_token" edge to the AgentToken entity.
func (_u *AgentDMMessageUpdateOne) SetAgentToken(v *AgentToken) *AgentDMMessageUpdateOne {
	return _u.SetAgentTokenID(v.ID)
}

// Mutation returns the AgentDMMessageMutation object of the builder.
func (_u *AgentDMMessageUpdateOne) Mutation() *AgentDMMessageMutation {
	return _u.mutation
}

// ClearAgentToken clears the "agent_token" edge to the AgentToken entity.
func (_u *AgentDMMessageUpdateOne) ClearAgentToken() *AgentDMMessageUpdateOne {
	_u.mutation.ClearAgentToken()
	return _u
}

// Where appends a list predicates to the AgentDMMessageUpdate builder.
func (_u *AgentDMMessageUpdateOne) Where(ps ...predicate.AgentDMMessage) *AgentDMMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentDMMessageUpdateOne) Select(field string, fields ...string) *AgentDMMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentDMMessage entity.
func (_u *AgentDMMessageUpdateOne) Save(ctx context.Context) (*AgentDMMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentDMMessageUpdateOne) SaveX(ctx context.Context) *AgentDMMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentDMMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentDMMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentDMMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentdmmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentDMMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := agentdmmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AgentDMMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := agentdmmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "AgentDMMessage.body": %w`, err)}
		}
	}
	if _u.mutation.AgentTokenCleared() && len(_u.mutation.AgentTokenIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentDMMessage.agent_token"`)
	}
	return nil
}

func (_u *AgentDMMessageUpdateOne) sqlSave(ctx context.Context) (_node *AgentDMMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentdmmessage.Table, agentdmmessage.Columns, sqlgraph.NewFieldSpec(agentdmmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentDMMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentdmmessage.FieldID)
		for _, f := range fields {
			if !agentdmmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentdmmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(agentdmmessage.FieldChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(agentdmmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(agentdmmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(agentdmmessage.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(agentdmmessage.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(agentdmmessage.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(agentdmmessage.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Edited(); ok {
		_spec.SetField(agentdmmessage.FieldEdited, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(agentdmmessage.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentdmmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AgentTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdmmessage.AgentTokenTable,
			Columns: []string{agentdmmessage.AgentTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdmmessage.AgentTokenTable,
			Columns: []string{agentdmmessage.AgentTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentDMMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentdmmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
