// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/alert"
	"alga/ent/alertevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AlertEventCreate is the builder for creating a AlertEvent entity.
type AlertEventCreate struct {
	config
	mutation *AlertEventMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *AlertEventCreate) SetType(v string) *AlertEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *AlertEventCreate) SetTimestamp(v time.Time) *AlertEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AlertEventCreate) SetNillableTimestamp(v *time.Time) *AlertEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetActorUsername sets the "actor_username" field.
func (_c *AlertEventCreate) SetActorUsername(v string) *AlertEventCreate {
	_c.mutation.SetActorUsername(v)
	return _c
}

// SetNillableActorUsername sets the "actor_username" field if the given value is not nil.
func (_c *AlertEventCreate) SetNillableActorUsername(v *string) *AlertEventCreate {
	if v != nil {
		_c.SetActorUsername(*v)
	}
	return _c
}

// SetActorDisplayName sets the "actor_display_name" field.
func (_c *AlertEventCreate) SetActorDisplayName(v string) *AlertEventCreate {
	_c.mutation.SetActorDisplayName(v)
	return _c
}

// SetNillableActorDisplayName sets the "actor_display_name" field if the given value is not nil.
func (_c *AlertEventCreate) SetNillableActorDisplayName(v *string) *AlertEventCreate {
	if v != nil {
		_c.SetActorDisplayName(*v)
	}
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *AlertEventCreate) SetActorUserID(v string) *AlertEventCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *AlertEventCreate) SetNillableActorUserID(v *string) *AlertEventCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *AlertEventCreate) SetSource(v string) *AlertEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *AlertEventCreate) SetNillableSource(v *string) *AlertEventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetAlertID sets the "alert_id" field.
func (_c *AlertEventCreate) SetAlertID(v uuid.UUID) *AlertEventCreate {
	_c.mutation.SetAlertID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AlertEventCreate) SetID(v uuid.UUID) *AlertEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AlertEventCreate) SetNillableID(v *uuid.UUID) *AlertEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAlert sets the "alert" edge to the Alert entity.
func (_c *AlertEventCreate) SetAlert(v *Alert) *AlertEventCreate {
	return _c.SetAlertID(v.ID)
}

// Mutation returns the AlertEventMutation object of the builder.
func (_c *AlertEventCreate) Mutation() *AlertEventMutation {
	return _c.mutation
}

// Save creates the AlertEvent in the database.
func (_c *AlertEventCreate) Save(ctx context.Context) (*AlertEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AlertEventCreate) SaveX(ctx context.Context) *AlertEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AlertEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := alertevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.ActorUsername(); !ok {
		v := alertevent.DefaultActorUsername
		_c.mutation.SetActorUsername(v)
	}
	if _, ok := _c.mutation.ActorDisplayName(); !ok {
		v := alertevent.DefaultActorDisplayName
		_c.mutation.SetActorDisplayName(v)
	}
	if _, ok := _c.mutation.ActorUserID(); !ok {
		v := alertevent.DefaultActorUserID
		_c.mutation.SetActorUserID(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := alertevent.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := alertevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AlertEventCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AlertEvent.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := alertevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AlertEvent.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AlertEvent.timestamp"`)}
	}
	if _, ok := _c.mutation.AlertID(); !ok {
		return &ValidationError{Name: "alert_id", err: errors.New(`ent: missing required field "AlertEvent.alert_id"`)}
	}
	if len(_c.mutation.AlertIDs()) == 0 {
		return &ValidationError{Name: "alert", err: errors.New(`ent: missing required edge "AlertEvent.alert"`)}
	}
	return nil
}

func (_c *AlertEventCreate) sqlSave(ctx context.Context) (*AlertEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AlertEventCreate) createSpec() (*AlertEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(alertevent.Table, sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(alertevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(alertevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.ActorUsername(); ok {
		_spec.SetField(alertevent.FieldActorUsername, field.TypeString, value)
		_node.ActorUsername = value
	}
	if value, ok := _c.mutation.ActorDisplayName(); ok {
		_spec.SetField(alertevent.FieldActorDisplayName, field.TypeString, value)
		_node.ActorDisplayName = value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(alertevent.FieldActorUserID, field.TypeString, value)
		_node.ActorUserID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(alertevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if nodes := _c.mutation.AlertIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertevent.AlertTable,
			Columns: []string{alertevent.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AlertID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AlertEventCreateBulk is the builder for creating many AlertEvent entities in bulk.
type AlertEventCreateBulk struct {
	config
	err      error
	builders []*AlertEventCreate
}

// Save creates the AlertEvent entities in the database.
func (_c *AlertEventCreateBulk) Save(ctx context.Context) ([]*AlertEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AlertEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AlertEventCreateBulk) SaveX(ctx context.Context) []*AlertEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AlertEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AlertEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
