// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/auditlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (_c *AuditLogCreate) SetTimestamp(v time.Time) *AuditLogCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableTimestamp(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetEvent sets the "event" field.
func (_c *AuditLogCreate) SetEvent(v string) *AuditLogCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AuditLogCreate) SetUserID(v uuid.UUID) *AuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUserID(v *uuid.UUID) *AuditLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *AuditLogCreate) SetUsername(v string) *AuditLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUsername(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *AuditLogCreate) SetIP(v string) *AuditLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableIP(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AuditLogCreate) SetUserAgent(v string) *AuditLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUserAgent(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *AuditLogCreate) SetSuccess(v bool) *AuditLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableSuccess(v *bool) *AuditLogCreate {
	if v != nil {
		_c.SetSuccess(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *AuditLogCreate) SetDetails(v map[string]interface{}) *AuditLogCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AuditLogCreate) SetRequestID(v string) *AuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableRequestID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditLogCreate) SetID(v uuid.UUID) *AuditLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableID(v *uuid.UUID) *AuditLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AuditLogMutation object of the builder.
func (_c *AuditLogCreate) Mutation() *AuditLogMutation {
	return _c.mutation
}

// Save creates the AuditLog in the database.
func (_c *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditLogCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := auditlog.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := auditlog.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.IP(); !ok {
		v := auditlog.DefaultIP
		_c.mutation.SetIP(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := auditlog.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.Success(); !ok {
		v := auditlog.DefaultSuccess
		_c.mutation.SetSuccess(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := auditlog.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := auditlog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditLogCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AuditLog.timestamp"`)}
	}
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "AuditLog.event"`)}
	}
	if v, ok := _c.mutation.Event(); ok {
		if err := auditlog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "AuditLog.event": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "AuditLog.success"`)}
	}
	return nil
}

func (_c *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(auditlog.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(auditlog.FieldEvent, field.TypeString, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeUUID, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(auditlog.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(auditlog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(auditlog.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	return _node, _spec
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
}

// Save creates the AuditLog entities in the database.
func (_c *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
