// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/coordinationtask"
	"alga/ent/incident"
	"alga/ent/incidentinvestigation"
	"alga/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CoordinationTaskUpdate is the builder for updating CoordinationTask entities.
type CoordinationTaskUpdate struct {
	config
	hooks    []Hook
	mutation *CoordinationTaskMutation
}

// Where appends a list predicates to the CoordinationTaskUpdate builder.
func (_u *CoordinationTaskUpdate) Where(ps ...predicate.CoordinationTask) *CoordinationTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *CoordinationTaskUpdate) SetIncidentID(v uuid.UUID) *CoordinationTaskUpdate {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableIncidentID(v *uuid.UUID) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (_u *CoordinationTaskUpdate) ClearIncidentID() *CoordinationTaskUpdate {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *CoordinationTaskUpdate) SetParentTaskID(v uuid.UUID) *CoordinationTaskUpdate {
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableParentTaskID(v *uuid.UUID) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// ClearParentTaskID clears the value of the "parent_task_id" field.
func (_u *CoordinationTaskUpdate) ClearParentTaskID() *CoordinationTaskUpdate {
	_u.mutation.ClearParentTaskID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *CoordinationTaskUpdate) SetKind(v coordinationtask.Kind) *CoordinationTaskUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableKind(v *coordinationtask.Kind) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAssigneeRole sets the "assignee_role" field.
func (_u *CoordinationTaskUpdate) SetAssigneeRole(v coordinationtask.AssigneeRole) *CoordinationTaskUpdate {
	_u.mutation.SetAssigneeRole(v)
	return _u
}

// SetNillableAssigneeRole sets the "assignee_role" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableAssigneeRole(v *coordinationtask.AssigneeRole) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetAssigneeRole(*v)
	}
	return _u
}

// SetAssigneeAgentID sets the "assignee_agent_id" field.
func (_u *CoordinationTaskUpdate) SetAssigneeAgentID(v string) *CoordinationTaskUpdate {
	_u.mutation.SetAssigneeAgentID(v)
	return _u
}

// SetNillableAssigneeAgentID sets the "assignee_agent_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableAssigneeAgentID(v *string) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetAssigneeAgentID(*v)
	}
	return _u
}

// ClearAssigneeAgentID clears the value of the "assignee_agent_id" field.
func (_u *CoordinationTaskUpdate) ClearAssigneeAgentID() *CoordinationTaskUpdate {
	_u.mutation.ClearAssigneeAgentID()
	return _u
}

// SetAssigneeAgentName sets the "assignee_agent_name" field.
func (_u *CoordinationTaskUpdate) SetAssigneeAgentName(v string) *CoordinationTaskUpdate {
	_u.mutation.SetAssigneeAgentName(v)
	return _u
}

// SetNillableAssigneeAgentName sets the "assignee_agent_name" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableAssigneeAgentName(v *string) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetAssigneeAgentName(*v)
	}
	return _u
}

// ClearAssigneeAgentName clears the value of the "assignee_agent_name" field.
func (_u *CoordinationTaskUpdate) ClearAssigneeAgentName() *CoordinationTaskUpdate {
	_u.mutation.ClearAssigneeAgentName()
	return _u
}

// SetGoal sets the "goal" field.
func (_u *CoordinationTaskUpdate) SetGoal(v string) *CoordinationTaskUpdate {
	_u.mutation.SetGoal(v)
	return _u
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableGoal(v *string) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetGoal(*v)
	}
	return _u
}

// SetInputContext sets the "input_context" field.
func (_u *CoordinationTaskUpdate) SetInputContext(v map[string]interface{}) *CoordinationTaskUpdate {
	_u.mutation.SetInputContext(v)
	return _u
}

// SetResult sets the "result" field.
func (_u *CoordinationTaskUpdate) SetResult(v map[string]interface{}) *CoordinationTaskUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *CoordinationTaskUpdate) ClearResult() *CoordinationTaskUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetResultSchema sets the "result_schema" field.
func (_u *CoordinationTaskUpdate) SetResultSchema(v map[string]interface{}) *CoordinationTaskUpdate {
	_u.mutation.SetResultSchema(v)
	return _u
}

// ClearResultSchema clears the value of the "result_schema" field.
func (_u *CoordinationTaskUpdate) ClearResultSchema() *CoordinationTaskUpdate {
	_u.mutation.ClearResultSchema()
	return _u
}

// SetLinkedInvestigationID sets the "linked_investigation_id" field.
func (_u *CoordinationTaskUpdate) SetLinkedInvestigationID(v uuid.UUID) *CoordinationTaskUpdate {
	_u.mutation.SetLinkedInvestigationID(v)
	return _u
}

// SetNillableLinkedInvestigationID sets the "linked_investigation_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableLinkedInvestigationID(v *uuid.UUID) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetLinkedInvestigationID(*v)
	}
	return _u
}

// ClearLinkedInvestigationID clears the value of the "linked_investigation_id" field.
func (_u *CoordinationTaskUpdate) ClearLinkedInvestigationID() *CoordinationTaskUpdate {
	_u.mutation.ClearLinkedInvestigationID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoordinationTaskUpdate) SetStatus(v coordinationtask.Status) *CoordinationTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableStatus(v *coordinationtask.Status) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CoordinationTaskUpdate) SetPriority(v int) *CoordinationTaskUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillablePriority(v *int) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CoordinationTaskUpdate) AddPriority(v int) *CoordinationTaskUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *CoordinationTaskUpdate) SetDueAt(v time.Time) *CoordinationTaskUpdate {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableDueAt(v *time.Time) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// ClearDueAt clears the value of the "due_at" field.
func (_u *CoordinationTaskUpdate) ClearDueAt() *CoordinationTaskUpdate {
	_u.mutation.ClearDueAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *CoordinationTaskUpdate) SetClaimedAt(v time.Time) *CoordinationTaskUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableClaimedAt(v *time.Time) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *CoordinationTaskUpdate) ClearClaimedAt() *CoordinationTaskUpdate {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CoordinationTaskUpdate) SetCompletedAt(v time.Time) *CoordinationTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableCompletedAt(v *time.Time) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CoordinationTaskUpdate) ClearCompletedAt() *CoordinationTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCreatedByAgentID sets the "created_by_agent_id" field.
func (_u *CoordinationTaskUpdate) SetCreatedByAgentID(v string) *CoordinationTaskUpdate {
	_u.mutation.SetCreatedByAgentID(v)
	return _u
}

// SetNillableCreatedByAgentID sets the "created_by_agent_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableCreatedByAgentID(v *string) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetCreatedByAgentID(*v)
	}
	return _u
}

// ClearCreatedByAgentID clears the value of the "created_by_agent_id" field.
func (_u *CoordinationTaskUpdate) ClearCreatedByAgentID() *CoordinationTaskUpdate {
	_u.mutation.ClearCreatedByAgentID()
	return _u
}

// SetCreatedByName sets the "created_by_name" field.
func (_u *CoordinationTaskUpdate) SetCreatedByName(v string) *CoordinationTaskUpdate {
	_u.mutation.SetCreatedByName(v)
	return _u
}

// SetNillableCreatedByName sets the "created_by_name" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableCreatedByName(v *string) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetCreatedByName(*v)
	}
	return _u
}

// ClearCreatedByName clears the value of the "created_by_name" field.
func (_u *CoordinationTaskUpdate) ClearCreatedByName() *CoordinationTaskUpdate {
	_u.mutation.ClearCreatedByName()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *CoordinationTaskUpdate) SetFailureReason(v string) *CoordinationTaskUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableFailureReason(v *string) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *CoordinationTaskUpdate) ClearFailureReason() *CoordinationTaskUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetDispatchAttempts sets the "dispatch_attempts" field.
func (_u *CoordinationTaskUpdate) SetDispatchAttempts(v int) *CoordinationTaskUpdate {
	_u.mutation.ResetDispatchAttempts()
	_u.mutation.SetDispatchAttempts(v)
	return _u
}

// SetNillableDispatchAttempts sets the "dispatch_attempts" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableDispatchAttempts(v *int) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetDispatchAttempts(*v)
	}
	return _u
}

// AddDispatchAttempts adds value to the "dispatch_attempts" field.
func (_u *CoordinationTaskUpdate) AddDispatchAttempts(v int) *CoordinationTaskUpdate {
	_u.mutation.AddDispatchAttempts(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CoordinationTaskUpdate) SetCreatedAt(v time.Time) *CoordinationTaskUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdate) SetNillableCreatedAt(v *time.Time) *CoordinationTaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoordinationTaskUpdate) SetUpdatedAt(v time.Time) *CoordinationTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_u *CoordinationTaskUpdate) SetIncident(v *Incident) *CoordinationTaskUpdate {
	return _u.SetIncidentID(v.ID)
}

// AddChildTaskIDs adds the "child_tasks" edge to the CoordinationTask entity by IDs.
func (_u *CoordinationTaskUpdate) AddChildTaskIDs(ids ...uuid.UUID) *CoordinationTaskUpdate {
	_u.mutation.AddChildTaskIDs(ids...)
	return _u
}

// AddChildTasks adds the "child_tasks" edges to the CoordinationTask entity.
func (_u *CoordinationTaskUpdate) AddChildTasks(v ...*CoordinationTask) *CoordinationTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildTaskIDs(ids...)
}

// SetParentTask sets the "parent_task" edge to the CoordinationTask entity.
func (_u *CoordinationTaskUpdate) SetParentTask(v *CoordinationTask) *CoordinationTaskUpdate {
	return _u.SetParentTaskID(v.ID)
}

// SetLinkedInvestigation sets the "linked_investigation" edge to the IncidentInvestigation entity.
func (_u *CoordinationTaskUpdate) SetLinkedInvestigation(v *IncidentInvestigation) *CoordinationTaskUpdate {
	return _u.SetLinkedInvestigationID(v.ID)
}

// Mutation returns the CoordinationTaskMutation object of the builder.
func (_u *CoordinationTaskUpdate) Mutation() *CoordinationTaskMutation {
	return _u.mutation
}

// ClearIncident clears the "incident" edge to the Incident entity.
func (_u *CoordinationTaskUpdate) ClearIncident() *CoordinationTaskUpdate {
	_u.mutation.ClearIncident()
	return _u
}

// ClearChildTasks clears all "child_tasks" edges to the CoordinationTask entity.
func (_u *CoordinationTaskUpdate) ClearChildTasks() *CoordinationTaskUpdate {
	_u.mutation.ClearChildTasks()
	return _u
}

// RemoveChildTaskIDs removes the "child_tasks" edge to CoordinationTask entities by IDs.
func (_u *CoordinationTaskUpdate) RemoveChildTaskIDs(ids ...uuid.UUID) *CoordinationTaskUpdate {
	_u.mutation.RemoveChildTaskIDs(ids...)
	return _u
}

// RemoveChildTasks removes "child_tasks" edges to CoordinationTask entities.
func (_u *CoordinationTaskUpdate) RemoveChildTasks(v ...*CoordinationTask) *CoordinationTaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildTaskIDs(ids...)
}

// ClearParentTask clears the "parent_task" edge to the CoordinationTask entity.
func (_u *CoordinationTaskUpdate) ClearParentTask() *CoordinationTaskUpdate {
	_u.mutation.ClearParentTask()
	return _u
}

// ClearLinkedInvestigation clears the "linked_investigation" edge to the IncidentInvestigation entity.
func (_u *CoordinationTaskUpdate) ClearLinkedInvestigation() *CoordinationTaskUpdate {
	_u.mutation.ClearLinkedInvestigation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoordinationTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoordinationTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoordinationTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoordinationTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoordinationTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := coordinationtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoordinationTaskUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := coordinationtask.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssigneeRole(); ok {
		if err := coordinationtask.AssigneeRoleValidator(v); err != nil {
			return &ValidationError{Name: "assignee_role", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.assignee_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Goal(); ok {
		if err := coordinationtask.GoalValidator(v); err != nil {
			return &ValidationError{Name: "goal", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.goal": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := coordinationtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := coordinationtask.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DispatchAttempts(); ok {
		if err := coordinationtask.DispatchAttemptsValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_attempts", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.dispatch_attempts": %w`, err)}
		}
	}
	return nil
}

func (_u *CoordinationTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coordinationtask.Table, coordinationtask.Columns, sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(coordinationtask.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AssigneeRole(); ok {
		_spec.SetField(coordinationtask.FieldAssigneeRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AssigneeAgentID(); ok {
		_spec.SetField(coordinationtask.FieldAssigneeAgentID, field.TypeString, value)
	}
	if _u.mutation.AssigneeAgentIDCleared() {
		_spec.ClearField(coordinationtask.FieldAssigneeAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.AssigneeAgentName(); ok {
		_spec.SetField(coordinationtask.FieldAssigneeAgentName, field.TypeString, value)
	}
	if _u.mutation.AssigneeAgentNameCleared() {
		_spec.ClearField(coordinationtask.FieldAssigneeAgentName, field.TypeString)
	}
	if value, ok := _u.mutation.Goal(); ok {
		_spec.SetField(coordinationtask.FieldGoal, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputContext(); ok {
		_spec.SetField(coordinationtask.FieldInputContext, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(coordinationtask.FieldResult, field.TypeJSON, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(coordinationtask.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultSchema(); ok {
		_spec.SetField(coordinationtask.FieldResultSchema, field.TypeJSON, value)
	}
	if _u.mutation.ResultSchemaCleared() {
		_spec.ClearField(coordinationtask.FieldResultSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coordinationtask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(coordinationtask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(coordinationtask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(coordinationtask.FieldDueAt, field.TypeTime, value)
	}
	if _u.mutation.DueAtCleared() {
		_spec.ClearField(coordinationtask.FieldDueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(coordinationtask.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(coordinationtask.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(coordinationtask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(coordinationtask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedByAgentID(); ok {
		_spec.SetField(coordinationtask.FieldCreatedByAgentID, field.TypeString, value)
	}
	if _u.mutation.CreatedByAgentIDCleared() {
		_spec.ClearField(coordinationtask.FieldCreatedByAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedByName(); ok {
		_spec.SetField(coordinationtask.FieldCreatedByName, field.TypeString, value)
	}
	if _u.mutation.CreatedByNameCleared() {
		_spec.ClearField(coordinationtask.FieldCreatedByName, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(coordinationtask.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(coordinationtask.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.DispatchAttempts(); ok {
		_spec.SetField(coordinationtask.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDispatchAttempts(); ok {
		_spec.AddField(coordinationtask.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(coordinationtask.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coordinationtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.IncidentTable,
			Columns: []string{coordinationtask.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.IncidentTable,
			Columns: []string{coordinationtask.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coordinationtask.ChildTasksTable,
			Columns: []string{coordinationtask.ChildTasksColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildTasksIDs(); len(nodes) > 0 && !_u.mutation.ChildTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coordinationtask.ChildTasksTable,
			Columns: []string{coordinationtask.ChildTasksColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coordinationtask.ChildTasksTable,
			Columns: []string{coordinationtask.ChildTasksColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentTaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.ParentTaskTable,
			Columns: []string{coordinationtask.ParentTaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentTaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.ParentTaskTable,
			Columns: []string{coordinationtask.ParentTaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinkedInvestigationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.LinkedInvestigationTable,
			Columns: []string{coordinationtask.LinkedInvestigationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentinvestigation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkedInvestigationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.LinkedInvestigationTable,
			Columns: []string{coordinationtask.LinkedInvestigationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentinvestigation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coordinationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoordinationTaskUpdateOne is the builder for updating a single CoordinationTask entity.
type CoordinationTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CoordinationTaskMutation
}

// SetIncidentID sets the "incident_id" field.
func (_u *CoordinationTaskUpdateOne) SetIncidentID(v uuid.UUID) *CoordinationTaskUpdateOne {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableIncidentID(v *uuid.UUID) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (_u *CoordinationTaskUpdateOne) ClearIncidentID() *CoordinationTaskUpdateOne {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetParentTaskID sets the "parent_task_id" field.
func (_u *CoordinationTaskUpdateOne) SetParentTaskID(v uuid.UUID) *CoordinationTaskUpdateOne {
	_u.mutation.SetParentTaskID(v)
	return _u
}

// SetNillableParentTaskID sets the "parent_task_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableParentTaskID(v *uuid.UUID) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetParentTaskID(*v)
	}
	return _u
}

// ClearParentTaskID clears the value of the "parent_task_id" field.
func (_u *CoordinationTaskUpdateOne) ClearParentTaskID() *CoordinationTaskUpdateOne {
	_u.mutation.ClearParentTaskID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *CoordinationTaskUpdateOne) SetKind(v coordinationtask.Kind) *CoordinationTaskUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableKind(v *coordinationtask.Kind) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetAssigneeRole sets the "assignee_role" field.
func (_u *CoordinationTaskUpdateOne) SetAssigneeRole(v coordinationtask.AssigneeRole) *CoordinationTaskUpdateOne {
	_u.mutation.SetAssigneeRole(v)
	return _u
}

// SetNillableAssigneeRole sets the "assignee_role" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableAssigneeRole(v *coordinationtask.AssigneeRole) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetAssigneeRole(*v)
	}
	return _u
}

// SetAssigneeAgentID sets the "assignee_agent_id" field.
func (_u *CoordinationTaskUpdateOne) SetAssigneeAgentID(v string) *CoordinationTaskUpdateOne {
	_u.mutation.SetAssigneeAgentID(v)
	return _u
}

// SetNillableAssigneeAgentID sets the "assignee_agent_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableAssigneeAgentID(v *string) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetAssigneeAgentID(*v)
	}
	return _u
}

// ClearAssigneeAgentID clears the value of the "assignee_agent_id" field.
func (_u *CoordinationTaskUpdateOne) ClearAssigneeAgentID() *CoordinationTaskUpdateOne {
	_u.mutation.ClearAssigneeAgentID()
	return _u
}

// SetAssigneeAgentName sets the "assignee_agent_name" field.
func (_u *CoordinationTaskUpdateOne) SetAssigneeAgentName(v string) *CoordinationTaskUpdateOne {
	_u.mutation.SetAssigneeAgentName(v)
	return _u
}

// SetNillableAssigneeAgentName sets the "assignee_agent_name" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableAssigneeAgentName(v *string) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetAssigneeAgentName(*v)
	}
	return _u
}

// ClearAssigneeAgentName clears the value of the "assignee_agent_name" field.
func (_u *CoordinationTaskUpdateOne) ClearAssigneeAgentName() *CoordinationTaskUpdateOne {
	_u.mutation.ClearAssigneeAgentName()
	return _u
}

// SetGoal sets the "goal" field.
func (_u *CoordinationTaskUpdateOne) SetGoal(v string) *CoordinationTaskUpdateOne {
	_u.mutation.SetGoal(v)
	return _u
}

// SetNillableGoal sets the "goal" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableGoal(v *string) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetGoal(*v)
	}
	return _u
}

// SetInputContext sets the "input_context" field.
func (_u *CoordinationTaskUpdateOne) SetInputContext(v map[string]interface{}) *CoordinationTaskUpdateOne {
	_u.mutation.SetInputContext(v)
	return _u
}

// SetResult sets the "result" field.
func (_u *CoordinationTaskUpdateOne) SetResult(v map[string]interface{}) *CoordinationTaskUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *CoordinationTaskUpdateOne) ClearResult() *CoordinationTaskUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetResultSchema sets the "result_schema" field.
func (_u *CoordinationTaskUpdateOne) SetResultSchema(v map[string]interface{}) *CoordinationTaskUpdateOne {
	_u.mutation.SetResultSchema(v)
	return _u
}

// ClearResultSchema clears the value of the "result_schema" field.
func (_u *CoordinationTaskUpdateOne) ClearResultSchema() *CoordinationTaskUpdateOne {
	_u.mutation.ClearResultSchema()
	return _u
}

// SetLinkedInvestigationID sets the "linked_investigation_id" field.
func (_u *CoordinationTaskUpdateOne) SetLinkedInvestigationID(v uuid.UUID) *CoordinationTaskUpdateOne {
	_u.mutation.SetLinkedInvestigationID(v)
	return _u
}

// SetNillableLinkedInvestigationID sets the "linked_investigation_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableLinkedInvestigationID(v *uuid.UUID) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetLinkedInvestigationID(*v)
	}
	return _u
}

// ClearLinkedInvestigationID clears the value of the "linked_investigation_id" field.
func (_u *CoordinationTaskUpdateOne) ClearLinkedInvestigationID() *CoordinationTaskUpdateOne {
	_u.mutation.ClearLinkedInvestigationID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoordinationTaskUpdateOne) SetStatus(v coordinationtask.Status) *CoordinationTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableStatus(v *coordinationtask.Status) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CoordinationTaskUpdateOne) SetPriority(v int) *CoordinationTaskUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillablePriority(v *int) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CoordinationTaskUpdateOne) AddPriority(v int) *CoordinationTaskUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *CoordinationTaskUpdateOne) SetDueAt(v time.Time) *CoordinationTaskUpdateOne {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableDueAt(v *time.Time) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// ClearDueAt clears the value of the "due_at" field.
func (_u *CoordinationTaskUpdateOne) ClearDueAt() *CoordinationTaskUpdateOne {
	_u.mutation.ClearDueAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *CoordinationTaskUpdateOne) SetClaimedAt(v time.Time) *CoordinationTaskUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableClaimedAt(v *time.Time) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *CoordinationTaskUpdateOne) ClearClaimedAt() *CoordinationTaskUpdateOne {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CoordinationTaskUpdateOne) SetCompletedAt(v time.Time) *CoordinationTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CoordinationTaskUpdateOne) ClearCompletedAt() *CoordinationTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCreatedByAgentID sets the "created_by_agent_id" field.
func (_u *CoordinationTaskUpdateOne) SetCreatedByAgentID(v string) *CoordinationTaskUpdateOne {
	_u.mutation.SetCreatedByAgentID(v)
	return _u
}

// SetNillableCreatedByAgentID sets the "created_by_agent_id" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableCreatedByAgentID(v *string) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetCreatedByAgentID(*v)
	}
	return _u
}

// ClearCreatedByAgentID clears the value of the "created_by_agent_id" field.
func (_u *CoordinationTaskUpdateOne) ClearCreatedByAgentID() *CoordinationTaskUpdateOne {
	_u.mutation.ClearCreatedByAgentID()
	return _u
}

// SetCreatedByName sets the "created_by_name" field.
func (_u *CoordinationTaskUpdateOne) SetCreatedByName(v string) *CoordinationTaskUpdateOne {
	_u.mutation.SetCreatedByName(v)
	return _u
}

// SetNillableCreatedByName sets the "created_by_name" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableCreatedByName(v *string) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetCreatedByName(*v)
	}
	return _u
}

// ClearCreatedByName clears the value of the "created_by_name" field.
func (_u *CoordinationTaskUpdateOne) ClearCreatedByName() *CoordinationTaskUpdateOne {
	_u.mutation.ClearCreatedByName()
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *CoordinationTaskUpdateOne) SetFailureReason(v string) *CoordinationTaskUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableFailureReason(v *string) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *CoordinationTaskUpdateOne) ClearFailureReason() *CoordinationTaskUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetDispatchAttempts sets the "dispatch_attempts" field.
func (_u *CoordinationTaskUpdateOne) SetDispatchAttempts(v int) *CoordinationTaskUpdateOne {
	_u.mutation.ResetDispatchAttempts()
	_u.mutation.SetDispatchAttempts(v)
	return _u
}

// SetNillableDispatchAttempts sets the "dispatch_attempts" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableDispatchAttempts(v *int) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetDispatchAttempts(*v)
	}
	return _u
}

// AddDispatchAttempts adds value to the "dispatch_attempts" field.
func (_u *CoordinationTaskUpdateOne) AddDispatchAttempts(v int) *CoordinationTaskUpdateOne {
	_u.mutation.AddDispatchAttempts(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CoordinationTaskUpdateOne) SetCreatedAt(v time.Time) *CoordinationTaskUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CoordinationTaskUpdateOne) SetNillableCreatedAt(v *time.Time) *CoordinationTaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoordinationTaskUpdateOne) SetUpdatedAt(v time.Time) *CoordinationTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_u *CoordinationTaskUpdateOne) SetIncident(v *Incident) *CoordinationTaskUpdateOne {
	return _u.SetIncidentID(v.ID)
}

// AddChildTaskIDs adds the "child_tasks" edge to the CoordinationTask entity by IDs.
func (_u *CoordinationTaskUpdateOne) AddChildTaskIDs(ids ...uuid.UUID) *CoordinationTaskUpdateOne {
	_u.mutation.AddChildTaskIDs(ids...)
	return _u
}

// AddChildTasks adds the "child_tasks" edges to the CoordinationTask entity.
func (_u *CoordinationTaskUpdateOne) AddChildTasks(v ...*CoordinationTask) *CoordinationTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildTaskIDs(ids...)
}

// SetParentTask sets the "parent_task" edge to the CoordinationTask entity.
func (_u *CoordinationTaskUpdateOne) SetParentTask(v *CoordinationTask) *CoordinationTaskUpdateOne {
	return _u.SetParentTaskID(v.ID)
}

// SetLinkedInvestigation sets the "linked_investigation" edge to the IncidentInvestigation entity.
func (_u *CoordinationTaskUpdateOne) SetLinkedInvestigation(v *IncidentInvestigation) *CoordinationTaskUpdateOne {
	return _u.SetLinkedInvestigationID(v.ID)
}

// Mutation returns the CoordinationTaskMutation object of the builder.
func (_u *CoordinationTaskUpdateOne) Mutation() *CoordinationTaskMutation {
	return _u.mutation
}

// ClearIncident clears the "incident" edge to the Incident entity.
func (_u *CoordinationTaskUpdateOne) ClearIncident() *CoordinationTaskUpdateOne {
	_u.mutation.ClearIncident()
	return _u
}

// ClearChildTasks clears all "child_tasks" edges to the CoordinationTask entity.
func (_u *CoordinationTaskUpdateOne) ClearChildTasks() *CoordinationTaskUpdateOne {
	_u.mutation.ClearChildTasks()
	return _u
}

// RemoveChildTaskIDs removes the "child_tasks" edge to CoordinationTask entities by IDs.
func (_u *CoordinationTaskUpdateOne) RemoveChildTaskIDs(ids ...uuid.UUID) *CoordinationTaskUpdateOne {
	_u.mutation.RemoveChildTaskIDs(ids...)
	return _u
}

// RemoveChildTasks removes "child_tasks" edges to CoordinationTask entities.
func (_u *CoordinationTaskUpdateOne) RemoveChildTasks(v ...*CoordinationTask) *CoordinationTaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildTaskIDs(ids...)
}

// ClearParentTask clears the "parent_task" edge to the CoordinationTask entity.
func (_u *CoordinationTaskUpdateOne) ClearParentTask() *CoordinationTaskUpdateOne {
	_u.mutation.ClearParentTask()
	return _u
}

// ClearLinkedInvestigation clears the "linked_investigation" edge to the IncidentInvestigation entity.
func (_u *CoordinationTaskUpdateOne) ClearLinkedInvestigation() *CoordinationTaskUpdateOne {
	_u.mutation.ClearLinkedInvestigation()
	return _u
}

// Where appends a list predicates to the CoordinationTaskUpdate builder.
func (_u *CoordinationTaskUpdateOne) Where(ps ...predicate.CoordinationTask) *CoordinationTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoordinationTaskUpdateOne) Select(field string, fields ...string) *CoordinationTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CoordinationTask entity.
func (_u *CoordinationTaskUpdateOne) Save(ctx context.Context) (*CoordinationTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoordinationTaskUpdateOne) SaveX(ctx context.Context) *CoordinationTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoordinationTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoordinationTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoordinationTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := coordinationtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CoordinationTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := coordinationtask.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssigneeRole(); ok {
		if err := coordinationtask.AssigneeRoleValidator(v); err != nil {
			return &ValidationError{Name: "assignee_role", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.assignee_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Goal(); ok {
		if err := coordinationtask.GoalValidator(v); err != nil {
			return &ValidationError{Name: "goal", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.goal": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := coordinationtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := coordinationtask.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DispatchAttempts(); ok {
		if err := coordinationtask.DispatchAttemptsValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_attempts", err: fmt.Errorf(`ent: validator failed for field "CoordinationTask.dispatch_attempts": %w`, err)}
		}
	}
	return nil
}

func (_u *CoordinationTaskUpdateOne) sqlSave(ctx context.Context) (_node *CoordinationTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coordinationtask.Table, coordinationtask.Columns, sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CoordinationTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coordinationtask.FieldID)
		for _, f := range fields {
			if !coordinationtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coordinationtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(coordinationtask.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AssigneeRole(); ok {
		_spec.SetField(coordinationtask.FieldAssigneeRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AssigneeAgentID(); ok {
		_spec.SetField(coordinationtask.FieldAssigneeAgentID, field.TypeString, value)
	}
	if _u.mutation.AssigneeAgentIDCleared() {
		_spec.ClearField(coordinationtask.FieldAssigneeAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.AssigneeAgentName(); ok {
		_spec.SetField(coordinationtask.FieldAssigneeAgentName, field.TypeString, value)
	}
	if _u.mutation.AssigneeAgentNameCleared() {
		_spec.ClearField(coordinationtask.FieldAssigneeAgentName, field.TypeString)
	}
	if value, ok := _u.mutation.Goal(); ok {
		_spec.SetField(coordinationtask.FieldGoal, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputContext(); ok {
		_spec.SetField(coordinationtask.FieldInputContext, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(coordinationtask.FieldResult, field.TypeJSON, value)
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(coordinationtask.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultSchema(); ok {
		_spec.SetField(coordinationtask.FieldResultSchema, field.TypeJSON, value)
	}
	if _u.mutation.ResultSchemaCleared() {
		_spec.ClearField(coordinationtask.FieldResultSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coordinationtask.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(coordinationtask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(coordinationtask.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(coordinationtask.FieldDueAt, field.TypeTime, value)
	}
	if _u.mutation.DueAtCleared() {
		_spec.ClearField(coordinationtask.FieldDueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(coordinationtask.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(coordinationtask.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(coordinationtask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(coordinationtask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedByAgentID(); ok {
		_spec.SetField(coordinationtask.FieldCreatedByAgentID, field.TypeString, value)
	}
	if _u.mutation.CreatedByAgentIDCleared() {
		_spec.ClearField(coordinationtask.FieldCreatedByAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedByName(); ok {
		_spec.SetField(coordinationtask.FieldCreatedByName, field.TypeString, value)
	}
	if _u.mutation.CreatedByNameCleared() {
		_spec.ClearField(coordinationtask.FieldCreatedByName, field.TypeString)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(coordinationtask.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(coordinationtask.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.DispatchAttempts(); ok {
		_spec.SetField(coordinationtask.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDispatchAttempts(); ok {
		_spec.AddField(coordinationtask.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(coordinationtask.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coordinationtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.IncidentTable,
			Columns: []string{coordinationtask.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.IncidentTable,
			Columns: []string{coordinationtask.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coordinationtask.ChildTasksTable,
			Columns: []string{coordinationtask.ChildTasksColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildTasksIDs(); len(nodes) > 0 && !_u.mutation.ChildTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coordinationtask.ChildTasksTable,
			Columns: []string{coordinationtask.ChildTasksColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coordinationtask.ChildTasksTable,
			Columns: []string{coordinationtask.ChildTasksColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentTaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.ParentTaskTable,
			Columns: []string{coordinationtask.ParentTaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentTaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.ParentTaskTable,
			Columns: []string{coordinationtask.ParentTaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coordinationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinkedInvestigationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.LinkedInvestigationTable,
			Columns: []string{coordinationtask.LinkedInvestigationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentinvestigation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkedInvestigationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coordinationtask.LinkedInvestigationTable,
			Columns: []string{coordinationtask.LinkedInvestigationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentinvestigation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CoordinationTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coordinationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
