// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/investigationthread"
	"alga/ent/investigationthreadmessage"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// InvestigationThreadMessageCreate is the builder for creating a InvestigationThreadMessage entity.
type InvestigationThreadMessageCreate struct {
	config
	mutation *InvestigationThreadMessageMutation
	hooks    []Hook
}

// SetThreadUUID sets the "thread_uuid" field.
func (_c *InvestigationThreadMessageCreate) SetThreadUUID(v uuid.UUID) *InvestigationThreadMessageCreate {
	_c.mutation.SetThreadUUID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *InvestigationThreadMessageCreate) SetType(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableType(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *InvestigationThreadMessageCreate) SetSource(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableSource(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *InvestigationThreadMessageCreate) SetMessage(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetInternal sets the "internal" field.
func (_c *InvestigationThreadMessageCreate) SetInternal(v bool) *InvestigationThreadMessageCreate {
	_c.mutation.SetInternal(v)
	return _c
}

// SetNillableInternal sets the "internal" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableInternal(v *bool) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetInternal(*v)
	}
	return _c
}

// SetEdited sets the "edited" field.
func (_c *InvestigationThreadMessageCreate) SetEdited(v bool) *InvestigationThreadMessageCreate {
	_c.mutation.SetEdited(v)
	return _c
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableEdited(v *bool) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetEdited(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InvestigationThreadMessageCreate) SetUserID(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableUserID(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *InvestigationThreadMessageCreate) SetUsername(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableUsername(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetAgentType sets the "agent_type" field.
func (_c *InvestigationThreadMessageCreate) SetAgentType(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetAgentType(v)
	return _c
}

// SetNillableAgentType sets the "agent_type" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableAgentType(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetAgentType(*v)
	}
	return _c
}

// SetMmPostID sets the "mm_post_id" field.
func (_c *InvestigationThreadMessageCreate) SetMmPostID(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetMmPostID(v)
	return _c
}

// SetNillableMmPostID sets the "mm_post_id" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableMmPostID(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetMmPostID(*v)
	}
	return _c
}

// SetSlackMessageTs sets the "slack_message_ts" field.
func (_c *InvestigationThreadMessageCreate) SetSlackMessageTs(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetSlackMessageTs(v)
	return _c
}

// SetNillableSlackMessageTs sets the "slack_message_ts" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableSlackMessageTs(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetSlackMessageTs(*v)
	}
	return _c
}

// SetReplyToMessageID sets the "reply_to_message_id" field.
func (_c *InvestigationThreadMessageCreate) SetReplyToMessageID(v string) *InvestigationThreadMessageCreate {
	_c.mutation.SetReplyToMessageID(v)
	return _c
}

// SetNillableReplyToMessageID sets the "reply_to_message_id" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableReplyToMessageID(v *string) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetReplyToMessageID(*v)
	}
	return _c
}

// SetMentions sets the "mentions" field.
func (_c *InvestigationThreadMessageCreate) SetMentions(v []string) *InvestigationThreadMessageCreate {
	_c.mutation.SetMentions(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvestigationThreadMessageCreate) SetCreatedAt(v time.Time) *InvestigationThreadMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableCreatedAt(v *time.Time) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvestigationThreadMessageCreate) SetUpdatedAt(v time.Time) *InvestigationThreadMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableUpdatedAt(v *time.Time) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InvestigationThreadMessageCreate) SetID(v uuid.UUID) *InvestigationThreadMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InvestigationThreadMessageCreate) SetNillableID(v *uuid.UUID) *InvestigationThreadMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetThreadID sets the "thread" edge to the InvestigationThread entity by ID.
func (_c *InvestigationThreadMessageCreate) SetThreadID(id uuid.UUID) *InvestigationThreadMessageCreate {
	_c.mutation.SetThreadID(id)
	return _c
}

// SetThread sets the "thread" edge to the InvestigationThread entity.
func (_c *InvestigationThreadMessageCreate) SetThread(v *InvestigationThread) *InvestigationThreadMessageCreate {
	return _c.SetThreadID(v.ID)
}

// Mutation returns the InvestigationThreadMessageMutation object of the builder.
func (_c *InvestigationThreadMessageCreate) Mutation() *InvestigationThreadMessageMutation {
	return _c.mutation
}

// Save creates the InvestigationThreadMessage in the database.
func (_c *InvestigationThreadMessageCreate) Save(ctx context.Context) (*InvestigationThreadMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvestigationThreadMessageCreate) SaveX(ctx context.Context) *InvestigationThreadMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvestigationThreadMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvestigationThreadMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvestigationThreadMessageCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := investigationthreadmessage.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := investigationthreadmessage.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Internal(); !ok {
		v := investigationthreadmessage.DefaultInternal
		_c.mutation.SetInternal(v)
	}
	if _, ok := _c.mutation.Edited(); !ok {
		v := investigationthreadmessage.DefaultEdited
		_c.mutation.SetEdited(v)
	}
	if _, ok := _c.mutation.UserID(); !ok {
		v := investigationthreadmessage.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := investigationthreadmessage.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.AgentType(); !ok {
		v := investigationthreadmessage.DefaultAgentType
		_c.mutation.SetAgentType(v)
	}
	if _, ok := _c.mutation.MmPostID(); !ok {
		v := investigationthreadmessage.DefaultMmPostID
		_c.mutation.SetMmPostID(v)
	}
	if _, ok := _c.mutation.SlackMessageTs(); !ok {
		v := investigationthreadmessage.DefaultSlackMessageTs
		_c.mutation.SetSlackMessageTs(v)
	}
	if _, ok := _c.mutation.ReplyToMessageID(); !ok {
		v := investigationthreadmessage.DefaultReplyToMessageID
		_c.mutation.SetReplyToMessageID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := investigationthreadmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := investigationthreadmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := investigationthreadmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvestigationThreadMessageCreate) check() error {
	if _, ok := _c.mutation.ThreadUUID(); !ok {
		return &ValidationError{Name: "thread_uuid", err: errors.New(`ent: missing required field "InvestigationThreadMessage.thread_uuid"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "InvestigationThreadMessage.type"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "InvestigationThreadMessage.source"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "InvestigationThreadMessage.message"`)}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := investigationthreadmessage.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "InvestigationThreadMessage.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Internal(); !ok {
		return &ValidationError{Name: "internal", err: errors.New(`ent: missing required field "InvestigationThreadMessage.internal"`)}
	}
	if _, ok := _c.mutation.Edited(); !ok {
		return &ValidationError{Name: "edited", err: errors.New(`ent: missing required field "InvestigationThreadMessage.edited"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvestigationThreadMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvestigationThreadMessage.updated_at"`)}
	}
	if len(_c.mutation.ThreadIDs()) == 0 {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required edge "InvestigationThreadMessage.thread"`)}
	}
	return nil
}

func (_c *InvestigationThreadMessageCreate) sqlSave(ctx context.Context) (*InvestigationThreadMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvestigationThreadMessageCreate) createSpec() (*InvestigationThreadMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &InvestigationThreadMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(investigationthreadmessage.Table, sqlgraph.NewFieldSpec(investigationthreadmessage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(investigationthreadmessage.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(investigationthreadmessage.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(investigationthreadmessage.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Internal(); ok {
		_spec.SetField(investigationthreadmessage.FieldInternal, field.TypeBool, value)
		_node.Internal = value
	}
	if value, ok := _c.mutation.Edited(); ok {
		_spec.SetField(investigationthreadmessage.FieldEdited, field.TypeBool, value)
		_node.Edited = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(investigationthreadmessage.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(investigationthreadmessage.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.AgentType(); ok {
		_spec.SetField(investigationthreadmessage.FieldAgentType, field.TypeString, value)
		_node.AgentType = value
	}
	if value, ok := _c.mutation.MmPostID(); ok {
		_spec.SetField(investigationthreadmessage.FieldMmPostID, field.TypeString, value)
		_node.MmPostID = value
	}
	if value, ok := _c.mutation.SlackMessageTs(); ok {
		_spec.SetField(investigationthreadmessage.FieldSlackMessageTs, field.TypeString, value)
		_node.SlackMessageTs = value
	}
	if value, ok := _c.mutation.ReplyToMessageID(); ok {
		_spec.SetField(investigationthreadmessage.FieldReplyToMessageID, field.TypeString, value)
		_node.ReplyToMessageID = value
	}
	if value, ok := _c.mutation.Mentions(); ok {
		_spec.SetField(investigationthreadmessage.FieldMentions, field.TypeJSON, value)
		_node.Mentions = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(investigationthreadmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(investigationthreadmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   investigationthreadmessage.ThreadTable,
			Columns: []string{investigationthreadmessage.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(investigationthread.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThreadUUID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InvestigationThreadMessageCreateBulk is the builder for creating many InvestigationThreadMessage entities in bulk.
type InvestigationThreadMessageCreateBulk struct {
	config
	err      error
	builders []*InvestigationThreadMessageCreate
}

// Save creates the InvestigationThreadMessage entities in the database.
func (_c *InvestigationThreadMessageCreateBulk) Save(ctx context.Context) ([]*InvestigationThreadMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvestigationThreadMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvestigationThreadMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvestigationThreadMessageCreateBulk) SaveX(ctx context.Context) []*InvestigationThreadMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvestigationThreadMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvestigationThreadMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
