// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/postmortem"
	"alga/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostMortemUpdate is the builder for updating PostMortem entities.
type PostMortemUpdate struct {
	config
	hooks    []Hook
	mutation *PostMortemMutation
}

// Where appends a list predicates to the PostMortemUpdate builder.
func (_u *PostMortemUpdate) Where(ps ...predicate.PostMortem) *PostMortemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *PostMortemUpdate) SetIncidentID(v uuid.UUID) *PostMortemUpdate {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableIncidentID(v *uuid.UUID) *PostMortemUpdate {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostMortemUpdate) SetTitle(v string) *PostMortemUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableTitle(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostMortemUpdate) SetStatus(v string) *PostMortemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableStatus(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostMortemUpdate) SetSummary(v string) *PostMortemUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableSummary(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetTimeline sets the "timeline" field.
func (_u *PostMortemUpdate) SetTimeline(v []map[string]interface{}) *PostMortemUpdate {
	_u.mutation.SetTimeline(v)
	return _u
}

// AppendTimeline appends value to the "timeline" field.
func (_u *PostMortemUpdate) AppendTimeline(v []map[string]interface{}) *PostMortemUpdate {
	_u.mutation.AppendTimeline(v)
	return _u
}

// ClearTimeline clears the value of the "timeline" field.
func (_u *PostMortemUpdate) ClearTimeline() *PostMortemUpdate {
	_u.mutation.ClearTimeline()
	return _u
}

// SetRootCause sets the "root_cause" field.
func (_u *PostMortemUpdate) SetRootCause(v string) *PostMortemUpdate {
	_u.mutation.SetRootCause(v)
	return _u
}

// SetNillableRootCause sets the "root_cause" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableRootCause(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetRootCause(*v)
	}
	return _u
}

// SetContributingFactors sets the "contributing_factors" field.
func (_u *PostMortemUpdate) SetContributingFactors(v []string) *PostMortemUpdate {
	_u.mutation.SetContributingFactors(v)
	return _u
}

// AppendContributingFactors appends value to the "contributing_factors" field.
func (_u *PostMortemUpdate) AppendContributingFactors(v []string) *PostMortemUpdate {
	_u.mutation.AppendContributingFactors(v)
	return _u
}

// ClearContributingFactors clears the value of the "contributing_factors" field.
func (_u *PostMortemUpdate) ClearContributingFactors() *PostMortemUpdate {
	_u.mutation.ClearContributingFactors()
	return _u
}

// SetImpact sets the "impact" field.
func (_u *PostMortemUpdate) SetImpact(v string) *PostMortemUpdate {
	_u.mutation.SetImpact(v)
	return _u
}

// SetNillableImpact sets the "impact" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableImpact(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetImpact(*v)
	}
	return _u
}

// SetLessonsLearned sets the "lessons_learned" field.
func (_u *PostMortemUpdate) SetLessonsLearned(v string) *PostMortemUpdate {
	_u.mutation.SetLessonsLearned(v)
	return _u
}

// SetNillableLessonsLearned sets the "lessons_learned" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableLessonsLearned(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetLessonsLearned(*v)
	}
	return _u
}

// SetWhatWentWell sets the "what_went_well" field.
func (_u *PostMortemUpdate) SetWhatWentWell(v string) *PostMortemUpdate {
	_u.mutation.SetWhatWentWell(v)
	return _u
}

// SetNillableWhatWentWell sets the "what_went_well" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableWhatWentWell(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetWhatWentWell(*v)
	}
	return _u
}

// SetWhatWentWrong sets the "what_went_wrong" field.
func (_u *PostMortemUpdate) SetWhatWentWrong(v string) *PostMortemUpdate {
	_u.mutation.SetWhatWentWrong(v)
	return _u
}

// SetNillableWhatWentWrong sets the "what_went_wrong" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableWhatWentWrong(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetWhatWentWrong(*v)
	}
	return _u
}

// SetBlamelessConfirmed sets the "blameless_confirmed" field.
func (_u *PostMortemUpdate) SetBlamelessConfirmed(v bool) *PostMortemUpdate {
	_u.mutation.SetBlamelessConfirmed(v)
	return _u
}

// SetNillableBlamelessConfirmed sets the "blameless_confirmed" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableBlamelessConfirmed(v *bool) *PostMortemUpdate {
	if v != nil {
		_u.SetBlamelessConfirmed(*v)
	}
	return _u
}

// SetBlamelessNotes sets the "blameless_notes" field.
func (_u *PostMortemUpdate) SetBlamelessNotes(v string) *PostMortemUpdate {
	_u.mutation.SetBlamelessNotes(v)
	return _u
}

// SetNillableBlamelessNotes sets the "blameless_notes" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableBlamelessNotes(v *string) *PostMortemUpdate {
	if v != nil {
		_u.SetBlamelessNotes(*v)
	}
	return _u
}

// SetApprovedByID sets the "approved_by_id" field.
func (_u *PostMortemUpdate) SetApprovedByID(v uuid.UUID) *PostMortemUpdate {
	_u.mutation.SetApprovedByID(v)
	return _u
}

// SetNillableApprovedByID sets the "approved_by_id" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableApprovedByID(v *uuid.UUID) *PostMortemUpdate {
	if v != nil {
		_u.SetApprovedByID(*v)
	}
	return _u
}

// ClearApprovedByID clears the value of the "approved_by_id" field.
func (_u *PostMortemUpdate) ClearApprovedByID() *PostMortemUpdate {
	_u.mutation.ClearApprovedByID()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostMortemUpdate) SetPublishedAt(v time.Time) *PostMortemUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillablePublishedAt(v *time.Time) *PostMortemUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostMortemUpdate) ClearPublishedAt() *PostMortemUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PostMortemUpdate) SetCreatedAt(v time.Time) *PostMortemUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PostMortemUpdate) SetNillableCreatedAt(v *time.Time) *PostMortemUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostMortemUpdate) SetUpdatedAt(v time.Time) *PostMortemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PostMortemMutation object of the builder.
func (_u *PostMortemUpdate) Mutation() *PostMortemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostMortemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostMortemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostMortemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostMortemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostMortemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := postmortem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PostMortemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(postmortem.Table, postmortem.Columns, sqlgraph.NewFieldSpec(postmortem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IncidentID(); ok {
		_spec.SetField(postmortem.FieldIncidentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(postmortem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(postmortem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(postmortem.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timeline(); ok {
		_spec.SetField(postmortem.FieldTimeline, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTimeline(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, postmortem.FieldTimeline, value)
		})
	}
	if _u.mutation.TimelineCleared() {
		_spec.ClearField(postmortem.FieldTimeline, field.TypeJSON)
	}
	if value, ok := _u.mutation.RootCause(); ok {
		_spec.SetField(postmortem.FieldRootCause, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContributingFactors(); ok {
		_spec.SetField(postmortem.FieldContributingFactors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContributingFactors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, postmortem.FieldContributingFactors, value)
		})
	}
	if _u.mutation.ContributingFactorsCleared() {
		_spec.ClearField(postmortem.FieldContributingFactors, field.TypeJSON)
	}
	if value, ok := _u.mutation.Impact(); ok {
		_spec.SetField(postmortem.FieldImpact, field.TypeString, value)
	}
	if value, ok := _u.mutation.LessonsLearned(); ok {
		_spec.SetField(postmortem.FieldLessonsLearned, field.TypeString, value)
	}
	if value, ok := _u.mutation.WhatWentWell(); ok {
		_spec.SetField(postmortem.FieldWhatWentWell, field.TypeString, value)
	}
	if value, ok := _u.mutation.WhatWentWrong(); ok {
		_spec.SetField(postmortem.FieldWhatWentWrong, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlamelessConfirmed(); ok {
		_spec.SetField(postmortem.FieldBlamelessConfirmed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BlamelessNotes(); ok {
		_spec.SetField(postmortem.FieldBlamelessNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedByID(); ok {
		_spec.SetField(postmortem.FieldApprovedByID, field.TypeUUID, value)
	}
	if _u.mutation.ApprovedByIDCleared() {
		_spec.ClearField(postmortem.FieldApprovedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(postmortem.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(postmortem.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(postmortem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(postmortem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postmortem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostMortemUpdateOne is the builder for updating a single PostMortem entity.
type PostMortemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMortemMutation
}

// SetIncidentID sets the "incident_id" field.
func (_u *PostMortemUpdateOne) SetIncidentID(v uuid.UUID) *PostMortemUpdateOne {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableIncidentID(v *uuid.UUID) *PostMortemUpdateOne {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostMortemUpdateOne) SetTitle(v string) *PostMortemUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableTitle(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostMortemUpdateOne) SetStatus(v string) *PostMortemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableStatus(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostMortemUpdateOne) SetSummary(v string) *PostMortemUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableSummary(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetTimeline sets the "timeline" field.
func (_u *PostMortemUpdateOne) SetTimeline(v []map[string]interface{}) *PostMortemUpdateOne {
	_u.mutation.SetTimeline(v)
	return _u
}

// AppendTimeline appends value to the "timeline" field.
func (_u *PostMortemUpdateOne) AppendTimeline(v []map[string]interface{}) *PostMortemUpdateOne {
	_u.mutation.AppendTimeline(v)
	return _u
}

// ClearTimeline clears the value of the "timeline" field.
func (_u *PostMortemUpdateOne) ClearTimeline() *PostMortemUpdateOne {
	_u.mutation.ClearTimeline()
	return _u
}

// SetRootCause sets the "root_cause" field.
func (_u *PostMortemUpdateOne) SetRootCause(v string) *PostMortemUpdateOne {
	_u.mutation.SetRootCause(v)
	return _u
}

// SetNillableRootCause sets the "root_cause" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableRootCause(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetRootCause(*v)
	}
	return _u
}

// SetContributingFactors sets the "contributing_factors" field.
func (_u *PostMortemUpdateOne) SetContributingFactors(v []string) *PostMortemUpdateOne {
	_u.mutation.SetContributingFactors(v)
	return _u
}

// AppendContributingFactors appends value to the "contributing_factors" field.
func (_u *PostMortemUpdateOne) AppendContributingFactors(v []string) *PostMortemUpdateOne {
	_u.mutation.AppendContributingFactors(v)
	return _u
}

// ClearContributingFactors clears the value of the "contributing_factors" field.
func (_u *PostMortemUpdateOne) ClearContributingFactors() *PostMortemUpdateOne {
	_u.mutation.ClearContributingFactors()
	return _u
}

// SetImpact sets the "impact" field.
func (_u *PostMortemUpdateOne) SetImpact(v string) *PostMortemUpdateOne {
	_u.mutation.SetImpact(v)
	return _u
}

// SetNillableImpact sets the "impact" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableImpact(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetImpact(*v)
	}
	return _u
}

// SetLessonsLearned sets the "lessons_learned" field.
func (_u *PostMortemUpdateOne) SetLessonsLearned(v string) *PostMortemUpdateOne {
	_u.mutation.SetLessonsLearned(v)
	return _u
}

// SetNillableLessonsLearned sets the "lessons_learned" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableLessonsLearned(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetLessonsLearned(*v)
	}
	return _u
}

// SetWhatWentWell sets the "what_went_well" field.
func (_u *PostMortemUpdateOne) SetWhatWentWell(v string) *PostMortemUpdateOne {
	_u.mutation.SetWhatWentWell(v)
	return _u
}

// SetNillableWhatWentWell sets the "what_went_well" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableWhatWentWell(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetWhatWentWell(*v)
	}
	return _u
}

// SetWhatWentWrong sets the "what_went_wrong" field.
func (_u *PostMortemUpdateOne) SetWhatWentWrong(v string) *PostMortemUpdateOne {
	_u.mutation.SetWhatWentWrong(v)
	return _u
}

// SetNillableWhatWentWrong sets the "what_went_wrong" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableWhatWentWrong(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetWhatWentWrong(*v)
	}
	return _u
}

// SetBlamelessConfirmed sets the "blameless_confirmed" field.
func (_u *PostMortemUpdateOne) SetBlamelessConfirmed(v bool) *PostMortemUpdateOne {
	_u.mutation.SetBlamelessConfirmed(v)
	return _u
}

// SetNillableBlamelessConfirmed sets the "blameless_confirmed" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableBlamelessConfirmed(v *bool) *PostMortemUpdateOne {
	if v != nil {
		_u.SetBlamelessConfirmed(*v)
	}
	return _u
}

// SetBlamelessNotes sets the "blameless_notes" field.
func (_u *PostMortemUpdateOne) SetBlamelessNotes(v string) *PostMortemUpdateOne {
	_u.mutation.SetBlamelessNotes(v)
	return _u
}

// SetNillableBlamelessNotes sets the "blameless_notes" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableBlamelessNotes(v *string) *PostMortemUpdateOne {
	if v != nil {
		_u.SetBlamelessNotes(*v)
	}
	return _u
}

// SetApprovedByID sets the "approved_by_id" field.
func (_u *PostMortemUpdateOne) SetApprovedByID(v uuid.UUID) *PostMortemUpdateOne {
	_u.mutation.SetApprovedByID(v)
	return _u
}

// SetNillableApprovedByID sets the "approved_by_id" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableApprovedByID(v *uuid.UUID) *PostMortemUpdateOne {
	if v != nil {
		_u.SetApprovedByID(*v)
	}
	return _u
}

// ClearApprovedByID clears the value of the "approved_by_id" field.
func (_u *PostMortemUpdateOne) ClearApprovedByID() *PostMortemUpdateOne {
	_u.mutation.ClearApprovedByID()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostMortemUpdateOne) SetPublishedAt(v time.Time) *PostMortemUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillablePublishedAt(v *time.Time) *PostMortemUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostMortemUpdateOne) ClearPublishedAt() *PostMortemUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PostMortemUpdateOne) SetCreatedAt(v time.Time) *PostMortemUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PostMortemUpdateOne) SetNillableCreatedAt(v *time.Time) *PostMortemUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostMortemUpdateOne) SetUpdatedAt(v time.Time) *PostMortemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PostMortemMutation object of the builder.
func (_u *PostMortemUpdateOne) Mutation() *PostMortemMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostMortemUpdate builder.
func (_u *PostMortemUpdateOne) Where(ps ...predicate.PostMortem) *PostMortemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostMortemUpdateOne) Select(field string, fields ...string) *PostMortemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostMortem entity.
func (_u *PostMortemUpdateOne) Save(ctx context.Context) (*PostMortem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostMortemUpdateOne) SaveX(ctx context.Context) *PostMortem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostMortemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostMortemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostMortemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := postmortem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PostMortemUpdateOne) sqlSave(ctx context.Context) (_node *PostMortem, err error) {
	_spec := sqlgraph.NewUpdateSpec(postmortem.Table, postmortem.Columns, sqlgraph.NewFieldSpec(postmortem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostMortem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postmortem.FieldID)
		for _, f := range fields {
			if !postmortem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postmortem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IncidentID(); ok {
		_spec.SetField(postmortem.FieldIncidentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(postmortem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(postmortem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(postmortem.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timeline(); ok {
		_spec.SetField(postmortem.FieldTimeline, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTimeline(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, postmortem.FieldTimeline, value)
		})
	}
	if _u.mutation.TimelineCleared() {
		_spec.ClearField(postmortem.FieldTimeline, field.TypeJSON)
	}
	if value, ok := _u.mutation.RootCause(); ok {
		_spec.SetField(postmortem.FieldRootCause, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContributingFactors(); ok {
		_spec.SetField(postmortem.FieldContributingFactors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContributingFactors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, postmortem.FieldContributingFactors, value)
		})
	}
	if _u.mutation.ContributingFactorsCleared() {
		_spec.ClearField(postmortem.FieldContributingFactors, field.TypeJSON)
	}
	if value, ok := _u.mutation.Impact(); ok {
		_spec.SetField(postmortem.FieldImpact, field.TypeString, value)
	}
	if value, ok := _u.mutation.LessonsLearned(); ok {
		_spec.SetField(postmortem.FieldLessonsLearned, field.TypeString, value)
	}
	if value, ok := _u.mutation.WhatWentWell(); ok {
		_spec.SetField(postmortem.FieldWhatWentWell, field.TypeString, value)
	}
	if value, ok := _u.mutation.WhatWentWrong(); ok {
		_spec.SetField(postmortem.FieldWhatWentWrong, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlamelessConfirmed(); ok {
		_spec.SetField(postmortem.FieldBlamelessConfirmed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BlamelessNotes(); ok {
		_spec.SetField(postmortem.FieldBlamelessNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedByID(); ok {
		_spec.SetField(postmortem.FieldApprovedByID, field.TypeUUID, value)
	}
	if _u.mutation.ApprovedByIDCleared() {
		_spec.ClearField(postmortem.FieldApprovedByID, field.TypeUUID)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(postmortem.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(postmortem.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(postmortem.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(postmortem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PostMortem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postmortem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
