// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/predicate"
	"alga/ent/statuspage"
	"alga/ent/statuspagecomponent"
	"alga/ent/team"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StatusPageUpdate is the builder for updating StatusPage entities.
type StatusPageUpdate struct {
	config
	hooks    []Hook
	mutation *StatusPageMutation
}

// Where appends a list predicates to the StatusPageUpdate builder.
func (_u *StatusPageUpdate) Where(ps ...predicate.StatusPage) *StatusPageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StatusPageUpdate) SetName(v string) *StatusPageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableName(v *string) *StatusPageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *StatusPageUpdate) SetSlug(v string) *StatusPageUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableSlug(v *string) *StatusPageUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *StatusPageUpdate) SetDescription(v string) *StatusPageUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableDescription(v *string) *StatusPageUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *StatusPageUpdate) SetVisibility(v statuspage.Visibility) *StatusPageUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableVisibility(v *statuspage.Visibility) *StatusPageUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *StatusPageUpdate) SetEnabled(v bool) *StatusPageUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableEnabled(v *bool) *StatusPageUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetOwnerTeamID sets the "owner_team_id" field.
func (_u *StatusPageUpdate) SetOwnerTeamID(v uuid.UUID) *StatusPageUpdate {
	_u.mutation.SetOwnerTeamID(v)
	return _u
}

// SetNillableOwnerTeamID sets the "owner_team_id" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableOwnerTeamID(v *uuid.UUID) *StatusPageUpdate {
	if v != nil {
		_u.SetOwnerTeamID(*v)
	}
	return _u
}

// ClearOwnerTeamID clears the value of the "owner_team_id" field.
func (_u *StatusPageUpdate) ClearOwnerTeamID() *StatusPageUpdate {
	_u.mutation.ClearOwnerTeamID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StatusPageUpdate) SetCreatedAt(v time.Time) *StatusPageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StatusPageUpdate) SetNillableCreatedAt(v *time.Time) *StatusPageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusPageUpdate) SetUpdatedAt(v time.Time) *StatusPageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddComponentIDs adds the "components" edge to the StatusPageComponent entity by IDs.
func (_u *StatusPageUpdate) AddComponentIDs(ids ...uuid.UUID) *StatusPageUpdate {
	_u.mutation.AddComponentIDs(ids...)
	return _u
}

// AddComponents adds the "components" edges to the StatusPageComponent entity.
func (_u *StatusPageUpdate) AddComponents(v ...*StatusPageComponent) *StatusPageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddComponentIDs(ids...)
}

// SetOwnerTeam sets the "owner_team" edge to the Team entity.
func (_u *StatusPageUpdate) SetOwnerTeam(v *Team) *StatusPageUpdate {
	return _u.SetOwnerTeamID(v.ID)
}

// Mutation returns the StatusPageMutation object of the builder.
func (_u *StatusPageUpdate) Mutation() *StatusPageMutation {
	return _u.mutation
}

// ClearComponents clears all "components" edges to the StatusPageComponent entity.
func (_u *StatusPageUpdate) ClearComponents() *StatusPageUpdate {
	_u.mutation.ClearComponents()
	return _u
}

// RemoveComponentIDs removes the "components" edge to StatusPageComponent entities by IDs.
func (_u *StatusPageUpdate) RemoveComponentIDs(ids ...uuid.UUID) *StatusPageUpdate {
	_u.mutation.RemoveComponentIDs(ids...)
	return _u
}

// RemoveComponents removes "components" edges to StatusPageComponent entities.
func (_u *StatusPageUpdate) RemoveComponents(v ...*StatusPageComponent) *StatusPageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveComponentIDs(ids...)
}

// ClearOwnerTeam clears the "owner_team" edge to the Team entity.
func (_u *StatusPageUpdate) ClearOwnerTeam() *StatusPageUpdate {
	_u.mutation.ClearOwnerTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusPageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusPageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusPageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusPageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusPageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statuspage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusPageUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := statuspage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusPage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := statuspage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "StatusPage.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := statuspage.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "StatusPage.visibility": %w`, err)}
		}
	}
	return nil
}

func (_u *StatusPageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statuspage.Table, statuspage.Columns, sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(statuspage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(statuspage.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(statuspage.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(statuspage.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(statuspage.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(statuspage.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statuspage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.ComponentsTable,
			Columns: []string{statuspage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedComponentsIDs(); len(nodes) > 0 && !_u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.ComponentsTable,
			Columns: []string{statuspage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.ComponentsTable,
			Columns: []string{statuspage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerTeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspage.OwnerTeamTable,
			Columns: []string{statuspage.OwnerTeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerTeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspage.OwnerTeamTable,
			Columns: []string{statuspage.OwnerTeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statuspage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusPageUpdateOne is the builder for updating a single StatusPage entity.
type StatusPageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusPageMutation
}

// SetName sets the "name" field.
func (_u *StatusPageUpdateOne) SetName(v string) *StatusPageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableName(v *string) *StatusPageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *StatusPageUpdateOne) SetSlug(v string) *StatusPageUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableSlug(v *string) *StatusPageUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *StatusPageUpdateOne) SetDescription(v string) *StatusPageUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableDescription(v *string) *StatusPageUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *StatusPageUpdateOne) SetVisibility(v statuspage.Visibility) *StatusPageUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableVisibility(v *statuspage.Visibility) *StatusPageUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *StatusPageUpdateOne) SetEnabled(v bool) *StatusPageUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableEnabled(v *bool) *StatusPageUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetOwnerTeamID sets the "owner_team_id" field.
func (_u *StatusPageUpdateOne) SetOwnerTeamID(v uuid.UUID) *StatusPageUpdateOne {
	_u.mutation.SetOwnerTeamID(v)
	return _u
}

// SetNillableOwnerTeamID sets the "owner_team_id" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableOwnerTeamID(v *uuid.UUID) *StatusPageUpdateOne {
	if v != nil {
		_u.SetOwnerTeamID(*v)
	}
	return _u
}

// ClearOwnerTeamID clears the value of the "owner_team_id" field.
func (_u *StatusPageUpdateOne) ClearOwnerTeamID() *StatusPageUpdateOne {
	_u.mutation.ClearOwnerTeamID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StatusPageUpdateOne) SetCreatedAt(v time.Time) *StatusPageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StatusPageUpdateOne) SetNillableCreatedAt(v *time.Time) *StatusPageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusPageUpdateOne) SetUpdatedAt(v time.Time) *StatusPageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddComponentIDs adds the "components" edge to the StatusPageComponent entity by IDs.
func (_u *StatusPageUpdateOne) AddComponentIDs(ids ...uuid.UUID) *StatusPageUpdateOne {
	_u.mutation.AddComponentIDs(ids...)
	return _u
}

// AddComponents adds the "components" edges to the StatusPageComponent entity.
func (_u *StatusPageUpdateOne) AddComponents(v ...*StatusPageComponent) *StatusPageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddComponentIDs(ids...)
}

// SetOwnerTeam sets the "owner_team" edge to the Team entity.
func (_u *StatusPageUpdateOne) SetOwnerTeam(v *Team) *StatusPageUpdateOne {
	return _u.SetOwnerTeamID(v.ID)
}

// Mutation returns the StatusPageMutation object of the builder.
func (_u *StatusPageUpdateOne) Mutation() *StatusPageMutation {
	return _u.mutation
}

// ClearComponents clears all "components" edges to the StatusPageComponent entity.
func (_u *StatusPageUpdateOne) ClearComponents() *StatusPageUpdateOne {
	_u.mutation.ClearComponents()
	return _u
}

// RemoveComponentIDs removes the "components" edge to StatusPageComponent entities by IDs.
func (_u *StatusPageUpdateOne) RemoveComponentIDs(ids ...uuid.UUID) *StatusPageUpdateOne {
	_u.mutation.RemoveComponentIDs(ids...)
	return _u
}

// RemoveComponents removes "components" edges to StatusPageComponent entities.
func (_u *StatusPageUpdateOne) RemoveComponents(v ...*StatusPageComponent) *StatusPageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveComponentIDs(ids...)
}

// ClearOwnerTeam clears the "owner_team" edge to the Team entity.
func (_u *StatusPageUpdateOne) ClearOwnerTeam() *StatusPageUpdateOne {
	_u.mutation.ClearOwnerTeam()
	return _u
}

// Where appends a list predicates to the StatusPageUpdate builder.
func (_u *StatusPageUpdateOne) Where(ps ...predicate.StatusPage) *StatusPageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusPageUpdateOne) Select(field string, fields ...string) *StatusPageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StatusPage entity.
func (_u *StatusPageUpdateOne) Save(ctx context.Context) (*StatusPage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusPageUpdateOne) SaveX(ctx context.Context) *StatusPage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusPageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusPageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusPageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statuspage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusPageUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := statuspage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusPage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := statuspage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "StatusPage.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := statuspage.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "StatusPage.visibility": %w`, err)}
		}
	}
	return nil
}

func (_u *StatusPageUpdateOne) sqlSave(ctx context.Context) (_node *StatusPage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statuspage.Table, statuspage.Columns, sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StatusPage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statuspage.FieldID)
		for _, f := range fields {
			if !statuspage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statuspage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(statuspage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(statuspage.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(statuspage.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(statuspage.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(statuspage.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(statuspage.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statuspage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.ComponentsTable,
			Columns: []string{statuspage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedComponentsIDs(); len(nodes) > 0 && !_u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.ComponentsTable,
			Columns: []string{statuspage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuspage.ComponentsTable,
			Columns: []string{statuspage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerTeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspage.OwnerTeamTable,
			Columns: []string{statuspage.OwnerTeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerTeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspage.OwnerTeamTable,
			Columns: []string{statuspage.OwnerTeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StatusPage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statuspage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
