// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/predicate"
	"alga/ent/service"
	"alga/ent/statuspage"
	"alga/ent/statuspagecomponent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StatusPageComponentUpdate is the builder for updating StatusPageComponent entities.
type StatusPageComponentUpdate struct {
	config
	hooks    []Hook
	mutation *StatusPageComponentMutation
}

// Where appends a list predicates to the StatusPageComponentUpdate builder.
func (_u *StatusPageComponentUpdate) Where(ps ...predicate.StatusPageComponent) *StatusPageComponentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatusPageID sets the "status_page_id" field.
func (_u *StatusPageComponentUpdate) SetStatusPageID(v uuid.UUID) *StatusPageComponentUpdate {
	_u.mutation.SetStatusPageID(v)
	return _u
}

// SetNillableStatusPageID sets the "status_page_id" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableStatusPageID(v *uuid.UUID) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetStatusPageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *StatusPageComponentUpdate) SetName(v string) *StatusPageComponentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableName(v *string) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *StatusPageComponentUpdate) SetDescription(v string) *StatusPageComponentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableDescription(v *string) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *StatusPageComponentUpdate) SetServiceID(v uuid.UUID) *StatusPageComponentUpdate {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableServiceID(v *uuid.UUID) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// ClearServiceID clears the value of the "service_id" field.
func (_u *StatusPageComponentUpdate) ClearServiceID() *StatusPageComponentUpdate {
	_u.mutation.ClearServiceID()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *StatusPageComponentUpdate) SetDisplayOrder(v int) *StatusPageComponentUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableDisplayOrder(v *int) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *StatusPageComponentUpdate) AddDisplayOrder(v int) *StatusPageComponentUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *StatusPageComponentUpdate) SetStatus(v statuspagecomponent.Status) *StatusPageComponentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableStatus(v *statuspagecomponent.Status) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StatusPageComponentUpdate) SetCreatedAt(v time.Time) *StatusPageComponentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StatusPageComponentUpdate) SetNillableCreatedAt(v *time.Time) *StatusPageComponentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusPageComponentUpdate) SetUpdatedAt(v time.Time) *StatusPageComponentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatusPage sets the "status_page" edge to the StatusPage entity.
func (_u *StatusPageComponentUpdate) SetStatusPage(v *StatusPage) *StatusPageComponentUpdate {
	return _u.SetStatusPageID(v.ID)
}

// SetService sets the "service" edge to the Service entity.
func (_u *StatusPageComponentUpdate) SetService(v *Service) *StatusPageComponentUpdate {
	return _u.SetServiceID(v.ID)
}

// Mutation returns the StatusPageComponentMutation object of the builder.
func (_u *StatusPageComponentUpdate) Mutation() *StatusPageComponentMutation {
	return _u.mutation
}

// ClearStatusPage clears the "status_page" edge to the StatusPage entity.
func (_u *StatusPageComponentUpdate) ClearStatusPage() *StatusPageComponentUpdate {
	_u.mutation.ClearStatusPage()
	return _u
}

// ClearService clears the "service" edge to the Service entity.
func (_u *StatusPageComponentUpdate) ClearService() *StatusPageComponentUpdate {
	_u.mutation.ClearService()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusPageComponentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusPageComponentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusPageComponentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusPageComponentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusPageComponentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statuspagecomponent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusPageComponentUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := statuspagecomponent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := statuspagecomponent.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.display_order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := statuspagecomponent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.status": %w`, err)}
		}
	}
	if _u.mutation.StatusPageCleared() && len(_u.mutation.StatusPageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusPageComponent.status_page"`)
	}
	return nil
}

func (_u *StatusPageComponentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statuspagecomponent.Table, statuspagecomponent.Columns, sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(statuspagecomponent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(statuspagecomponent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(statuspagecomponent.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(statuspagecomponent.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(statuspagecomponent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(statuspagecomponent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statuspagecomponent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StatusPageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.StatusPageTable,
			Columns: []string{statuspagecomponent.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusPageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.StatusPageTable,
			Columns: []string{statuspagecomponent.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.ServiceTable,
			Columns: []string{statuspagecomponent.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.ServiceTable,
			Columns: []string{statuspagecomponent.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statuspagecomponent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusPageComponentUpdateOne is the builder for updating a single StatusPageComponent entity.
type StatusPageComponentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusPageComponentMutation
}

// SetStatusPageID sets the "status_page_id" field.
func (_u *StatusPageComponentUpdateOne) SetStatusPageID(v uuid.UUID) *StatusPageComponentUpdateOne {
	_u.mutation.SetStatusPageID(v)
	return _u
}

// SetNillableStatusPageID sets the "status_page_id" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableStatusPageID(v *uuid.UUID) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetStatusPageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *StatusPageComponentUpdateOne) SetName(v string) *StatusPageComponentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableName(v *string) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *StatusPageComponentUpdateOne) SetDescription(v string) *StatusPageComponentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableDescription(v *string) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *StatusPageComponentUpdateOne) SetServiceID(v uuid.UUID) *StatusPageComponentUpdateOne {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableServiceID(v *uuid.UUID) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// ClearServiceID clears the value of the "service_id" field.
func (_u *StatusPageComponentUpdateOne) ClearServiceID() *StatusPageComponentUpdateOne {
	_u.mutation.ClearServiceID()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *StatusPageComponentUpdateOne) SetDisplayOrder(v int) *StatusPageComponentUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableDisplayOrder(v *int) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *StatusPageComponentUpdateOne) AddDisplayOrder(v int) *StatusPageComponentUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *StatusPageComponentUpdateOne) SetStatus(v statuspagecomponent.Status) *StatusPageComponentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableStatus(v *statuspagecomponent.Status) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StatusPageComponentUpdateOne) SetCreatedAt(v time.Time) *StatusPageComponentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StatusPageComponentUpdateOne) SetNillableCreatedAt(v *time.Time) *StatusPageComponentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusPageComponentUpdateOne) SetUpdatedAt(v time.Time) *StatusPageComponentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatusPage sets the "status_page" edge to the StatusPage entity.
func (_u *StatusPageComponentUpdateOne) SetStatusPage(v *StatusPage) *StatusPageComponentUpdateOne {
	return _u.SetStatusPageID(v.ID)
}

// SetService sets the "service" edge to the Service entity.
func (_u *StatusPageComponentUpdateOne) SetService(v *Service) *StatusPageComponentUpdateOne {
	return _u.SetServiceID(v.ID)
}

// Mutation returns the StatusPageComponentMutation object of the builder.
func (_u *StatusPageComponentUpdateOne) Mutation() *StatusPageComponentMutation {
	return _u.mutation
}

// ClearStatusPage clears the "status_page" edge to the StatusPage entity.
func (_u *StatusPageComponentUpdateOne) ClearStatusPage() *StatusPageComponentUpdateOne {
	_u.mutation.ClearStatusPage()
	return _u
}

// ClearService clears the "service" edge to the Service entity.
func (_u *StatusPageComponentUpdateOne) ClearService() *StatusPageComponentUpdateOne {
	_u.mutation.ClearService()
	return _u
}

// Where appends a list predicates to the StatusPageComponentUpdate builder.
func (_u *StatusPageComponentUpdateOne) Where(ps ...predicate.StatusPageComponent) *StatusPageComponentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusPageComponentUpdateOne) Select(field string, fields ...string) *StatusPageComponentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StatusPageComponent entity.
func (_u *StatusPageComponentUpdateOne) Save(ctx context.Context) (*StatusPageComponent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusPageComponentUpdateOne) SaveX(ctx context.Context) *StatusPageComponent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusPageComponentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusPageComponentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusPageComponentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statuspagecomponent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusPageComponentUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := statuspagecomponent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := statuspagecomponent.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.display_order": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := statuspagecomponent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.status": %w`, err)}
		}
	}
	if _u.mutation.StatusPageCleared() && len(_u.mutation.StatusPageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusPageComponent.status_page"`)
	}
	return nil
}

func (_u *StatusPageComponentUpdateOne) sqlSave(ctx context.Context) (_node *StatusPageComponent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statuspagecomponent.Table, statuspagecomponent.Columns, sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StatusPageComponent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statuspagecomponent.FieldID)
		for _, f := range fields {
			if !statuspagecomponent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statuspagecomponent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(statuspagecomponent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(statuspagecomponent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(statuspagecomponent.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(statuspagecomponent.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(statuspagecomponent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(statuspagecomponent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statuspagecomponent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StatusPageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.StatusPageTable,
			Columns: []string{statuspagecomponent.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusPageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.StatusPageTable,
			Columns: []string{statuspagecomponent.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.ServiceTable,
			Columns: []string{statuspagecomponent.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.ServiceTable,
			Columns: []string{statuspagecomponent.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StatusPageComponent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statuspagecomponent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
