// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alga/ent/service"
	"alga/ent/statuspage"
	"alga/ent/statuspagecomponent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StatusPageComponentCreate is the builder for creating a StatusPageComponent entity.
type StatusPageComponentCreate struct {
	config
	mutation *StatusPageComponentMutation
	hooks    []Hook
}

// SetStatusPageID sets the "status_page_id" field.
func (_c *StatusPageComponentCreate) SetStatusPageID(v uuid.UUID) *StatusPageComponentCreate {
	_c.mutation.SetStatusPageID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *StatusPageComponentCreate) SetName(v string) *StatusPageComponentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *StatusPageComponentCreate) SetDescription(v string) *StatusPageComponentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableDescription(v *string) *StatusPageComponentCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetServiceID sets the "service_id" field.
func (_c *StatusPageComponentCreate) SetServiceID(v uuid.UUID) *StatusPageComponentCreate {
	_c.mutation.SetServiceID(v)
	return _c
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableServiceID(v *uuid.UUID) *StatusPageComponentCreate {
	if v != nil {
		_c.SetServiceID(*v)
	}
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *StatusPageComponentCreate) SetDisplayOrder(v int) *StatusPageComponentCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableDisplayOrder(v *int) *StatusPageComponentCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StatusPageComponentCreate) SetStatus(v statuspagecomponent.Status) *StatusPageComponentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableStatus(v *statuspagecomponent.Status) *StatusPageComponentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StatusPageComponentCreate) SetCreatedAt(v time.Time) *StatusPageComponentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableCreatedAt(v *time.Time) *StatusPageComponentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StatusPageComponentCreate) SetUpdatedAt(v time.Time) *StatusPageComponentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableUpdatedAt(v *time.Time) *StatusPageComponentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StatusPageComponentCreate) SetID(v uuid.UUID) *StatusPageComponentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StatusPageComponentCreate) SetNillableID(v *uuid.UUID) *StatusPageComponentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetStatusPage sets the "status_page" edge to the StatusPage entity.
func (_c *StatusPageComponentCreate) SetStatusPage(v *StatusPage) *StatusPageComponentCreate {
	return _c.SetStatusPageID(v.ID)
}

// SetService sets the "service" edge to the Service entity.
func (_c *StatusPageComponentCreate) SetService(v *Service) *StatusPageComponentCreate {
	return _c.SetServiceID(v.ID)
}

// Mutation returns the StatusPageComponentMutation object of the builder.
func (_c *StatusPageComponentCreate) Mutation() *StatusPageComponentMutation {
	return _c.mutation
}

// Save creates the StatusPageComponent in the database.
func (_c *StatusPageComponentCreate) Save(ctx context.Context) (*StatusPageComponent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StatusPageComponentCreate) SaveX(ctx context.Context) *StatusPageComponent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusPageComponentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusPageComponentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StatusPageComponentCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := statuspagecomponent.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := statuspagecomponent.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := statuspagecomponent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := statuspagecomponent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := statuspagecomponent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := statuspagecomponent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StatusPageComponentCreate) check() error {
	if _, ok := _c.mutation.StatusPageID(); !ok {
		return &ValidationError{Name: "status_page_id", err: errors.New(`ent: missing required field "StatusPageComponent.status_page_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StatusPageComponent.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := statuspagecomponent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "StatusPageComponent.description"`)}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "StatusPageComponent.display_order"`)}
	}
	if v, ok := _c.mutation.DisplayOrder(); ok {
		if err := statuspagecomponent.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.display_order": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StatusPageComponent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := statuspagecomponent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StatusPageComponent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StatusPageComponent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StatusPageComponent.updated_at"`)}
	}
	if len(_c.mutation.StatusPageIDs()) == 0 {
		return &ValidationError{Name: "status_page", err: errors.New(`ent: missing required edge "StatusPageComponent.status_page"`)}
	}
	return nil
}

func (_c *StatusPageComponentCreate) sqlSave(ctx context.Context) (*StatusPageComponent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StatusPageComponentCreate) createSpec() (*StatusPageComponent, *sqlgraph.CreateSpec) {
	var (
		_node = &StatusPageComponent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(statuspagecomponent.Table, sqlgraph.NewFieldSpec(statuspagecomponent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(statuspagecomponent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(statuspagecomponent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(statuspagecomponent.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(statuspagecomponent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(statuspagecomponent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(statuspagecomponent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.StatusPageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.StatusPageTable,
			Columns: []string{statuspagecomponent.StatusPageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statuspage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StatusPageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   statuspagecomponent.ServiceTable,
			Columns: []string{statuspagecomponent.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServiceID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StatusPageComponentCreateBulk is the builder for creating many StatusPageComponent entities in bulk.
type StatusPageComponentCreateBulk struct {
	config
	err      error
	builders []*StatusPageComponentCreate
}

// Save creates the StatusPageComponent entities in the database.
func (_c *StatusPageComponentCreateBulk) Save(ctx context.Context) ([]*StatusPageComponent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StatusPageComponent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StatusPageComponentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StatusPageComponentCreateBulk) SaveX(ctx context.Context) []*StatusPageComponent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusPageComponentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusPageComponentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
