// Code generated by ent, DO NOT EDIT.

package triagerule

import (
	"alga/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldDescription, v))
}

// MatchMode applies equality check predicate on the "match_mode" field. It's identical to MatchModeEQ.
func MatchMode(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldMatchMode, v))
}

// Decision applies equality check predicate on the "decision" field. It's identical to DecisionEQ.
func Decision(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldDecision, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldSeverity, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldCategory, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldEnabled, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContainsFold(FieldDescription, v))
}

// ConditionsIsNil applies the IsNil predicate on the "conditions" field.
func ConditionsIsNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIsNull(FieldConditions))
}

// ConditionsNotNil applies the NotNil predicate on the "conditions" field.
func ConditionsNotNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotNull(FieldConditions))
}

// MatchModeEQ applies the EQ predicate on the "match_mode" field.
func MatchModeEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldMatchMode, v))
}

// MatchModeNEQ applies the NEQ predicate on the "match_mode" field.
func MatchModeNEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldMatchMode, v))
}

// MatchModeIn applies the In predicate on the "match_mode" field.
func MatchModeIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldMatchMode, vs...))
}

// MatchModeNotIn applies the NotIn predicate on the "match_mode" field.
func MatchModeNotIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldMatchMode, vs...))
}

// MatchModeGT applies the GT predicate on the "match_mode" field.
func MatchModeGT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldMatchMode, v))
}

// MatchModeGTE applies the GTE predicate on the "match_mode" field.
func MatchModeGTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldMatchMode, v))
}

// MatchModeLT applies the LT predicate on the "match_mode" field.
func MatchModeLT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldMatchMode, v))
}

// MatchModeLTE applies the LTE predicate on the "match_mode" field.
func MatchModeLTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldMatchMode, v))
}

// MatchModeContains applies the Contains predicate on the "match_mode" field.
func MatchModeContains(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContains(FieldMatchMode, v))
}

// MatchModeHasPrefix applies the HasPrefix predicate on the "match_mode" field.
func MatchModeHasPrefix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasPrefix(FieldMatchMode, v))
}

// MatchModeHasSuffix applies the HasSuffix predicate on the "match_mode" field.
func MatchModeHasSuffix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasSuffix(FieldMatchMode, v))
}

// MatchModeEqualFold applies the EqualFold predicate on the "match_mode" field.
func MatchModeEqualFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEqualFold(FieldMatchMode, v))
}

// MatchModeContainsFold applies the ContainsFold predicate on the "match_mode" field.
func MatchModeContainsFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContainsFold(FieldMatchMode, v))
}

// DecisionEQ applies the EQ predicate on the "decision" field.
func DecisionEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldDecision, v))
}

// DecisionNEQ applies the NEQ predicate on the "decision" field.
func DecisionNEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldDecision, v))
}

// DecisionIn applies the In predicate on the "decision" field.
func DecisionIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldDecision, vs...))
}

// DecisionNotIn applies the NotIn predicate on the "decision" field.
func DecisionNotIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldDecision, vs...))
}

// DecisionGT applies the GT predicate on the "decision" field.
func DecisionGT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldDecision, v))
}

// DecisionGTE applies the GTE predicate on the "decision" field.
func DecisionGTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldDecision, v))
}

// DecisionLT applies the LT predicate on the "decision" field.
func DecisionLT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldDecision, v))
}

// DecisionLTE applies the LTE predicate on the "decision" field.
func DecisionLTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldDecision, v))
}

// DecisionContains applies the Contains predicate on the "decision" field.
func DecisionContains(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContains(FieldDecision, v))
}

// DecisionHasPrefix applies the HasPrefix predicate on the "decision" field.
func DecisionHasPrefix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasPrefix(FieldDecision, v))
}

// DecisionHasSuffix applies the HasSuffix predicate on the "decision" field.
func DecisionHasSuffix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasSuffix(FieldDecision, v))
}

// DecisionEqualFold applies the EqualFold predicate on the "decision" field.
func DecisionEqualFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEqualFold(FieldDecision, v))
}

// DecisionContainsFold applies the ContainsFold predicate on the "decision" field.
func DecisionContainsFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContainsFold(FieldDecision, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityIsNil applies the IsNil predicate on the "severity" field.
func SeverityIsNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIsNull(FieldSeverity))
}

// SeverityNotNil applies the NotNil predicate on the "severity" field.
func SeverityNotNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotNull(FieldSeverity))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContainsFold(FieldSeverity, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryIsNil applies the IsNil predicate on the "category" field.
func CategoryIsNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIsNull(FieldCategory))
}

// CategoryNotNil applies the NotNil predicate on the "category" field.
func CategoryNotNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotNull(FieldCategory))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldContainsFold(FieldCategory, v))
}

// EnrichmentIsNil applies the IsNil predicate on the "enrichment" field.
func EnrichmentIsNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIsNull(FieldEnrichment))
}

// EnrichmentNotNil applies the NotNil predicate on the "enrichment" field.
func EnrichmentNotNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotNull(FieldEnrichment))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TriageRule {
	return predicate.TriageRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCreatedByUser applies the HasEdge predicate on the "created_by_user" edge.
func HasCreatedByUser() predicate.TriageRule {
	return predicate.TriageRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatedByUserTable, CreatedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedByUserWith applies the HasEdge predicate on the "created_by_user" edge with a given conditions (other predicates).
func HasCreatedByUserWith(preds ...predicate.User) predicate.TriageRule {
	return predicate.TriageRule(func(s *sql.Selector) {
		step := newCreatedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TriageRule) predicate.TriageRule {
	return predicate.TriageRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TriageRule) predicate.TriageRule {
	return predicate.TriageRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TriageRule) predicate.TriageRule {
	return predicate.TriageRule(sql.NotPredicates(p))
}
