apiVersion: v2
name: alga
description: AI-powered alert operations platform
type: application
version: 0.0.4
appVersion: "v0.0.2"
keywords:
  - alerting
  - sre
  - monitoring
  - grafana
  - self-hosted
home: https://github.com/hahnavi/alga
sources:
  - https://github.com/hahnavi/alga
maintainers:
  - name: hahnavi
